### ISSUE TITLE
Dual listbox

### ISSUE THREAD

**Issue by JostCrow** [michaelrambeau/bestofjs#100]
https://github.com/maykinmedia/dual-listbox

A dual listbox package that is just plain javascript

**Comment by michaelrambeau** [comment]
Hello @JostCrow 
Thank you for the recommendation.
Could you add some explanations to the repo on GitHub, starting with the project "description" that is empty, now.

Then I'd like to know: since the you provide no styling, what is the right way to style the component?
Just regular CSS I guess, but you could provide an example, maybe?

Could you provide a demo page, linked to the repo, with and without styling, so that users can see "Dual ListBox" in action?

One more thing, even if "Dual ListBox" is only a wrapper over a regular `<select>`, it would be nice to include among options a callback that fires every time a value is selected or unselected, so that the user does not have to deal with the `<options>` elements directly.

Thank you in advance!

**Comment by JostCrow** [comment]
The description is now filled.

There is some styling with the package. The styling can be found in the dist folder. I also added it to the README that there is a stylesheet.

I will create a demo page. When it is build I will let you know.

I will also work on the callback for any changes in selecting.

**Comment by michaelrambeau** [comment]
Thank you @JostCrow I will let you know as soon as `Dual listbox` is available on https://bestof.js.org/.

It's coming soon!

**Comment by michaelrambeau** [comment]
Hello @JostCrow 

`Dual listbox`project is now available on https://bestof.js.org/.

Check here for example: https://bestof.js.org/tags/plugin
