### ISSUE TITLE
ConsumerJS

### ISSUE THREAD

**Issue by JostCrow** [michaelrambeau/bestofjs#101]
https://github.com/maykinmedia/consumerjs

A REST API consumer (data store) built on top of aurelia-http-client with built-in (Django) csrf support.

**Comment by michaelrambeau** [comment]
Hello @JostCrow , this is your request number 3, thank you for your interest!

Is ConsumerJS limited to Aurelia framework, or can it work with any front-end framework?
For example, how does it work with the React eco-system?

Could you provide a full online demo, using data from a public API for example, so that users can see "ConsumerJS" in action?

Sorry to ask you so many questions, but BestOfJS is a curated list of projects, we try to gather the "best" projects rather than providing a full listing of projects, this is why I'm asking you for a more thorough documentation.
Thank you in advance!

**Comment by michaelrambeau** [comment]
Closing the issue because I didn't have feedback from @JostCrow 😢
