### ISSUE TITLE
Update openid-client and oauth4webapi

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#1019]
Please update the descriptions of

https://bestofjs.org/projects/openid-client to 

> OAuth 2 / OpenID Connect Client API for JavaScript Runtimes

https://bestofjs.org/projects/oauth4webapi to 

> Low-Level OAuth 2 / OpenID Connect Client API for JavaScript Runtimes

**Comment by michaelrambeau** [comment]
Hello Filip @panva thank you for the feedback.

Actually it was a bug as the project details page (`/projects/[slug]` URLs) shows the original description (when the project was added to _Best of JS_) instead of the actual one, pulled from GitHub.

It was fixed here: https://github.com/bestofjs/bestofjs/commit/78c0bf1f9691f623d06566fbf7442922b8fd771f

Could you check?

![image](https://github.com/user-attachments/assets/b94557e1-b6a2-4ab0-936d-c04441638c94)

**Comment by panva** [comment]
Thank you @michaelrambeau
