### ISSUE TITLE
Add `react-atomic/reshow` project

### ISSUE THREAD

**Issue by HillLiu** [michaelrambeau/bestofjs#12]
https://github.com/react-atomic/reshow
A simplified version of Flux, Just like redux + react-route + react + flux

**Comment by michaelrambeau** [comment]
Hello @HillLiu ,
I have checked 'reshow' project but I think it's not ready for production yet, it needs more documentation because it's difficult to understand what the project does right now.
In addition, there are already a lot of solutions that implement the 'flux' pattern: http://bestof.js.org/tags/flux
So I am not adding 'reshow' project right now, but I will consider it again when it's more mature because I don't want to miss "the next big thing" :)
Sorry for my negative answer, thank you for your understanding!

**Comment by HillLiu** [comment]
Sure, I just test it, will have a chance for re-apply when it's ready.  Thanks.
