### ISSUE TITLE
Add react-translated

### ISSUE THREAD

**Issue by amsul** [michaelrambeau/bestofjs#145]
Hi Michael! 👋 
I just published this https://github.com/amsul/react-translated and figured others may find it useful as well.

Thanks for the site!

**Comment by michaelrambeau** [comment]
Hello @amsul 
Thank you for the suggestion, `react-translated` will be available on bestof.js.org very soon.
Be patient!

**Comment by davojta** [comment]
@michaelrambeau do we really need one more project for i10n / i18n for react ? We already have 3 popular solutions for react, and have 4  options for general js apps. 

@amsul may be better to wait a little bit to gather more stars to add the solution to bestof.js.org ? What do you think ? )

**Comment by amsul** [comment]
> do we really need one more project for i10n / i18n for react

Probably not..but that doesn't stop me from experimenting with better ways of solving a problem :)

> may be better to wait a little bit to gather more stars to add the solution to bestof.js.org

Fair enough! I'm fine with that if that's a criteria. I was hoping it would get added based on its merit and the stars would just be a result of that.

**Comment by davojta** [comment]
@amsul I believe that if some tool has more then thousands start and a lot of forks it's formal criteria that some project doesnt rely on 1 contributor and there is a community around. Of course, if some project has strong will person and good quality ( tests, eslint, CI, readable and well structured self-documented code, a lot of user examples and answered questions on Stack overflow ) it could be great too. 

In any case, @michaelrambeau  is owner here and he will decide )

**Comment by michaelrambeau** [comment]
Hello @amsul 
Actually `react-translated` is available on bestof.js.org, check here: https://bestof.js.org/tags/i18n

It always takes 48 hours between the time I accept the request ("Coming soon" tag) and when it’s "live" ("Done" tag) because the application needs  at least 2 daily “snapshots” of GitHub stars, in order to display the trends.

@davojta I understand your concern, thank you for your comments.
To tell the truth, it’s hard to reject someone’s request, I know how much time and energy it takes to maintain an open source project. 
And I hate the feeling of rejection, when you do something with you heart, being rejected hurts...ah that feeling...
Nevertheless, we should try to find a way to curate "automatically" the list. For example we could say that _Best of JS_ is limited to 1000 projects based on a "score" (the most basic formula would be: number of stars * number of contributors). Projects beyond the 1000th rank would be in the waiting room. On the other hand, when a project starts, nobody knows it. So we have to find the right balance... well that should be an other thread, any suggestion is welcome!

**Comment by amsul** [comment]
@michaelrambeau agreed - there needs to be a balance there somehow. Sounds like a larger discussion around the goals of the site.

But anyways, I really appreciate you adding it in 💜 . Cheers!
