### ISSUE TITLE
React-styleguidist & Vue-styleguidist

### ISSUE THREAD

**Issue by rafaesc** [michaelrambeau/bestofjs#152]
Hi,
these are style guide generators for react and vue.

https://github.com/styleguidist/react-styleguidist
https://github.com/vue-styleguidist/vue-styleguidist

**Comment by michaelrambeau** [comment]
Hello @rafaesc 
Actually `react-styleguidist` is already available on bestof.js.org, check here:
https://bestof.js.org/tags/styleguide

![image](https://user-images.githubusercontent.com/5546996/34178028-16595d34-e549-11e7-8ce9-9f1a094f21ea.png)

Does it mean that bestof.js.org search feature does not work very well 😄 ?
I'm asking because we try to make the search feature as fast and efficient as possible.

So I'm going to add `vue-styleguidist` to the list, if you're OK.
Thank you in advance for your feedback!

**Comment by rafaesc** [comment]
Hi @michaelrambeau,

Thanks for response,
No, I didn't search well :sweat_smile:,
Only saw the [documentation section](https://bestof.js.org/tags/doc)

Ok, thanks for accepting the library, and for an awesome project.

Regards

**Comment by michaelrambeau** [comment]
@rafaesc No problem at all, thank you!

An other question, obviously `vue-styleguidist` is a project using `Vue.js` but `package.json` file includes several dependencies related to the React world:

```
 "react": "^15.6.1",
 "react-codemirror2": "^2.0.2",
 "react-dev-utils": "^3.0.2",
 "react-docgen": "^3.0.0-beta8",
 "react-docgen-displayname-handler": "^1.0.1",
 "react-dom": "^15.6.1",
 "react-group": "^1.0.5",
 "react-icons": "^2.2.7",
 "preact": "^8.2.1",
 "preact-compat": "^3.16.0",
 "react-test-renderer": "^15.6.1",
```

I wonder if it's normal?

**Comment by rafaesc** [comment]
Yes, because vue-styleguidist is a fork of react-styleguidist, but I added vue support.

The style guide's website is generated with react and the examples components are generated with vue. Similar to storybook and its vue support.

However, I need to remove the `react-docgen` and `preact` dependencies, because It doesn't use

**Comment by michaelrambeau** [comment]
@rafaesc  Alright, thank you for the information, I will let you know when it's available on bestof.js.org.

**Comment by rafaesc** [comment]
Thanks :smile:

**Comment by michaelrambeau** [comment]
Hello Rafael @rafaesc ,
It's online, please check here: https://bestof.js.org/tags/styleguide
Thank you!

**Comment by rafaesc** [comment]
Thank you!
