### ISSUE TITLE
Add pkg

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#153]
https://github.com/zeit/pkg

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq ,
Thank you again for your suggestion!
Could you tell me how could we tag this project?
All I know is that `pkg` is used to by the Zeit team to deliver their `Now` desktop application, could you tell me more about that project?
Thank you in advance for your help!

**Comment by gamtiq** [comment]
Hello Michael,
Actually I haven’t used this project yet so I cannot tell you anything besides official information.
I suppose `pkg` can be tagged as `Building tool`. Maybe `Compiler` tag also can be used.

**Comment by michaelrambeau** [comment]
Thank you @gamtiq Denis, 
For now, it will be tagged under 2 tags:

* `Node.js core` (https://bestof.js.org/tags/node.js) because somehow it generates executable files that include not only your application but also the **node.js core**.
* `Package - Dependency` (https://bestof.js.org/tags/package) because it's a tool that **packages** your code, your dependencies and the node.js core into one single file.

To me, projects currently under `Building tool` (developer workflow tools) and `Compiler` (languages that compile to JavaScript) seem too different... but it's really subtle, it's just a question of interpretation!

Does it make sense?
Again, thank you for your help Denis!

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq ,
It's online, check here: https://bestof.js.org/tags/package
Thank you!
