### ISSUE TITLE
Add env-hoc

### ISSUE THREAD

**Issue by supukarmin** [michaelrambeau/bestofjs#169]
Add [env-hoc](https://github.com/supukarmin/env-hoc).
> Provides a universal HOC (higher-order component) for Next.js / After.js and populates the component props and the getInitialProps args object with an env property, which gives access to cookies, IP address, language(s), userAgent and other variables on server-side and client-side in a standardized way.

**Comment by michaelrambeau** [comment]
Hello @supukarmin 
Thank you for the suggestion.
I wonder if `env-hov` can be used without Next.js / After.js, as a simple HOF to inject into wrapped components data about the browser context (cookies, IP address, language, userAgent) ?

I'm asking because currently it's difficult to tag a project that would only work with Next.js / After.js so it would be great if it could work in any React application, without being tight to a specific framework.

**Comment by supukarmin** [comment]
Version `1.2.1` works now with all React components, no need for a specific framework. Thank you for the suggestion, although the main benefit was to have these sort of data in client-side & server-side rendering in the same format.

**Comment by michaelrambeau** [comment]
Hello @supukarmin Thank you for the update, I've seen you updated the README.md, that's great!
`env-hoc` project will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @supukarmin `env-hoc` is available on _Best of JavaScript_.
