### ISSUE TITLE
three more entries for the table tag

### ISSUE THREAD

**Issue by wojdyr** [michaelrambeau/bestofjs#170]
Thanks for this helpful project.
Recently I looked at https://bestof.js.org/tags/table/ and here are some items that I think would fit there:

SlickGrid. It's a well-established project, but it's not that clear which repository to give.
The original one https://github.com/mleibman/SlickGrid has more stars, but is not developed anymore.
https://github.com/6pac/SlickGrid is the most active fork and "the acknowledged current master repository for SlickGrid".

Two others that look good to me are (both are relatively new):

https://github.com/ag-grid/ag-grid  3659 stars
https://github.com/olifolkerd/tabulator  483 stars

I'm not associated with any of the three projects.

**Comment by michaelrambeau** [comment]
Hello @wojdyr 
Thank you for the recommendation.
`ag-grid` and `tabulator` projects will be available on _Best of JS_ very soon.
About `SlickGrid`, because its situation is a bit confusing (the main repo is deprecated) and because we don't lack contenders in the category, it's maybe wiser to not add it for the moment.

**Comment by michaelrambeau** [comment]
Hello @wojdyr,  `ag-grid` and `tabulator` are available on _Best of JS_, please check here: https://bestof.js.org/tags/table

**Comment by wojdyr** [comment]
Thanks!
