### ISSUE TITLE
Add `rolling-scopes-school/js-assignments` project

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#19]
https://github.com/rolling-scopes-school/js-assignments
Set of js-assignments in TDD style for everyday dev tasks. Education stuff

**Comment by michaelrambeau** [comment]
Hello again @davojta , I am a bit reluctant to add it because we have just added `JS assessment` from Rebecca Murphy (as you suggested!).
That one does not seem either popular (41 stars) either actively maintained (all commits are between 6 and 7 months ago, nothing before, nothing after).
So I am keeping an eye on it for now... unless you tell me I really should add that project right now, because I trust my users ;)

**Comment by davojta** [comment]
yes, i agree that is not best of and should be rejected )
