### ISSUE TITLE
Add request: Tobi

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#190]
Hi!

I'd like to suggest adding [Tobi - An accessible, simple and light-weight open source lightbox script with no dependencies](https://github.com/rqrauhvmra/Tobi).

**Comment by michaelrambeau** [comment]
Hello Benjamin @rqrauhvmra ,
Thank you for the suggestion, it will be online very soon.

A quick remark: if `tobi` name is already taken on npm, maybe you could use "a scoped package" `@username/tobi` because the current package name `rqrauhvmra__tobi` looks a bit weird, I have never seen a package name with `__`... but it's not a big deal 😄

**Comment by ghost** [comment]
Hi @michaelrambeau 

Thanks. Also for the hint with _scoped packages_, I'll take a look.

**Comment by michaelrambeau** [comment]
Hello Benjamin @rqrauhvmra 

`Toby` project is available on _Best of JavaScript_,  check here: https://bestofjs.org/tags/viewer

**Comment by ghost** [comment]
Thanks @michaelrambeau
