### ISSUE TITLE
Suggesting Butterfly Server .NET

### ISSUE THREAD

**Issue by firesharkstudios** [michaelrambeau/bestofjs#191]
Butterfly Server .NET is an open source library which allows easily building the backend for real-time web apps and is a good fit for your "Real-time" category at https://bestofjs.org/tags/realtime.

Checkout https://butterflyserver.io (or https://github.com/firesharkstudios/butterfly-server-dotnet).

Thanks in advance for the consideration.

**Comment by michaelrambeau** [comment]
Hello Kent @firesharkstudios 
Thank you for the suggestion but we track in _Best of JavaScript_ only back-end solutions written with Node.js, but not solutions that rely on .NET (or any other technology like Rails or Python).

Your project looks good, and I noticed that the front-end part uses Vue but because of this reason I don't think it can be added to _Best of JavaScript_.

If the scope of _Best of JavaScript_ changes, we may reconsider our position of course.
Thank you for your understanding!

**Comment by firesharkstudios** [comment]
Make sense, no problem.  Love the site though.

**Comment by michaelrambeau** [comment]
@firesharkstudios Thank you Kent for your kind words, I can see you put a lot of effort in your project, keep up the good job! 😃
