### ISSUE TITLE
Add `kwhitley/apicache` project

### ISSUE THREAD

**Issue by TheBronx** [michaelrambeau/bestofjs#2]
https://github.com/kwhitley/apicache
Very simple and powerful module to add cache to JSON APIs

**Comment by michaelrambeau** [comment]
@TheBronx Thank you very much!

I am thinking about which tag could be used to categorize that project: maybe a new tag like **server middleware**, or **express middleware**, does it make sense for you, any idea ?

**Comment by TheBronx** [comment]
Thank you for this great project :+1: 

Express middleware makes sense. Maybe it is too broad, but for now it would be fine.

**Comment by michaelrambeau** [comment]
@TheBronx Thank you for your support, I added the project, it will be online in less than 48 hours (because the application needs at least data about Github stars about 2 different days, in order to display trends).

For your information, I am working now on integrating data from this application https://npms.io/ because they have a really nice system to "rate" npm modules.

I am curious to know how you use the application, if there is something that could be done to make it better or easier to use, from your point of view.
(I use the application as a super fast search engine when I need to access Github projects because I don't like to search through Github UI, it's slow and the results are full of irrelevant projects)

**Comment by TheBronx** [comment]
I use it as a way to see what's going on in the JS world. 
It is a good tool to see what are the "big hits" and news of the week/month. As you know JS evolves so fast... things like this project help a lot.
I've also had a look at some categories to check if there are any tools I've been using that could be replaced with better ones. Curiosity hehe.

I have been using it for at least two weeks and I find it easy to use and organized. If I find anything that could help you improve the site, I will let you know!

**Comment by michaelrambeau** [comment]
Thank you again, it's great to get feedback from real users 😎  !

**Comment by TheBronx** [comment]
Thank you too! Closing :+1:

**Comment by michaelrambeau** [comment]
@TheBronx it's online!

![image](https://cloud.githubusercontent.com/assets/5546996/16784294/07d7d002-48c3-11e6-9d26-37fd7652c029.png)
