### ISSUE TITLE
Add split-graphemes

### ISSUE THREAD

**Issue by martinheidegger** [michaelrambeau/bestofjs#206]
[`split-graphemes`](https://github.com/nota/split-graphemes) is a new library by nota but it looks very interesting.

**Comment by michaelrambeau** [comment]
Hello Martin @martinheidegger 
Thank you for the suggestion, it will be available on _Best of JS_ very soon.

Just to understand the context and to know how to "tag" it, do you know which problem it solves or how it's used at Nota?

The README says:

> You can simply use this library instead of Array.from to get graphemes.

but why would you use this library instead of `Array.from`?
(I suppose that it's the power of abstraction and that the library will cover more use-cases in the future?)

Thank you again and sorry if I missed something that is obvious!

**Comment by martinheidegger** [comment]
UTF-16 strings are hard to be split. Using graphemes it is possible to split a string that exceeds the UTF-8 space without ripping the meaning apart. The strings in the Array won't actually be "one-byte" long but rather "one-sensible-character"

**Comment by michaelrambeau** [comment]
Thank you Martin, it will be available under the tag "String" (https://bestofjs.org/tags/string) for now.

**Comment by michaelrambeau** [comment]
Hello Martin @martinheidegger 

`split-graphemes` is available on _Best of JavaScript_, please check here: https://bestofjs.org/tags/string
