### ISSUE TITLE
Add Sara Vieira

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#211]
Sara is an amazing developer and followed by a lot of developers as well, I do believe she deserves to be in the JS Hall of Fame :)

Her username: @saravieira

**Comment by michaelrambeau** [comment]
Thank you for the recommendation Sébastien @Atinux !

Actually I thought about adding members mentioned in this list https://github.com/SaraVieira/awesome-female-workshop-leads, one of the her repos.

Also I think somehow pagination and a search feature should be added to the _Hall of Fame_ because it's starting to be crowded (141 members right now).

**Comment by SaraVieira** [comment]
😍

Thank you both!

It's an honor to be there and all the women in that repo are amazing 💯

**Comment by michaelrambeau** [comment]
Hello @Atinux and @SaraVieira 

Thank you Sara, it's an honor that you visited _Best of JavaScript_ 😄 !

I searched for GitHub profiles from Sara's awesome list. The JavaScript _Hall of Fame_ has 8 new members!

Name | GitHub profile | Followers
--- | --- | ---
Sara Veira | https://github.com/SaraVieira | 1502
Eve Porcello | https://github.com/eveporcello | 192 | 
Manjula Subhashchandra Dube | https://github.com/manjula91 | 189
Marcy Sutton | https://github.com/marcysutton | 709
Simona Cotin | https://github.com/simonaco | 193
Peggy Rayzis | https://github.com/peggyrayzis | 722
Val Head | https://github.com/valhead | 115
Tara Vancil | https://github.com/taravancil | 521

Also `Beaker Browser` (from Tara Vancil) and `Axe` projects (from Marcy Sutton) will be available on _Best of JavaScript_ very soon.

Thank you for your feedback!

**Comment by atinux** [comment]
This is really nice, great work @michaelrambeau :)
