### ISSUE TITLE
Add safen

### ISSUE THREAD

**Issue by wan2land** [michaelrambeau/bestofjs#217]
https://github.com/corgidisco/safen

safen is an easy-to-use and fast validation library.

**Comment by michaelrambeau** [comment]
Hello @wan2land 
I was checking how Safen works, I was surprised that it uses a `String` variable to describe a schema, for example:

```js
`{
  area: {
    lat: number,
    lng: number,
  }
}`
```

To me it seems a bit brittle, it can be hard to detect a typo inside the string.

For example, if you type `Number` instead of `number`, you get the following error: `TypeError: testers[curr.name] is not a function`.

Since there are several contenders in this "validation" category (check here: https://bestofjs.org/tags/validation), it may be better to wait for some improvements about `safen`.

Let me know if my remarks make sense and sorry if I missed something obvious.
Thank you for your understanding!

**Comment by wan2land** [comment]
This issue has been fixed in v2.1.1 !

The error message has changed as follows. I can now see more clearly what the error is.

from
`TypeError: testers[curr.name] is not a function`

to
`Error: Undefined Error: "Number" is an undefined tester.`

**Comment by michaelrambeau** [comment]
Hello @wan2land 
Thank you for the fix.
In order to limit the numbers of projects included in _Best of JavaScript_ , from now, only projects with more than 50 stars are eligible.
To be able to show more projects (including yours!), the application needs a different architecture, now all the 1500 projects are loaded from a single JSON file when the application starts, it does not scale very well.
Sorry for this news, I'm keeping an eye on your project.
