### ISSUE TITLE
Please add Atlaskit

### ISSUE THREAD

**Issue by aliakakis** [michaelrambeau/bestofjs#221]
Hello. I would like to point to the following React based UI toolkit built by Atlassian https://atlaskit.atlassian.com/

**Comment by michaelrambeau** [comment]
Hello Antonios @aliakakis 
Thank you for the recommendation.
The project looks great but it's not on GitHub, the source code seems to be hosted on BitBucket.
_Best of JavaScript_ only tracks projects on GitHub, in order to show the trends, based on how the number of stargazers change everyday (and every week, every month... )
So it can't be tracked right now, I think, unless you have an idea to solve this issue.

**Comment by aliakakis** [comment]
Thank you for the reply :). You are absolutely right. Unfortunately there is no other way I can think of, unless JIRA decides to use GitHub as well.
