### ISSUE TITLE
Add redux-zap

### ISSUE THREAD

**Issue by Godefroy** [michaelrambeau/bestofjs#224]
Hi,

I'd like to add `redux-zap` to Best of JS, in the categories `State Management` and `Redux`.

https://github.com/lonestone/redux-zap
https://www.npmjs.com/package/redux-zap

Thanks!

**Comment by michaelrambeau** [comment]
Hello Godefroy @Godefroy 

Thank you for your suggestion.

Actually for now, only projects with more than 50 stars are displayed in _Best of JavaScript_,  the current architecture should be improved to accept more projects. 

Sorry I know it's unfair because when you start a new project it's normal to have no stars at all.

I will let you know when the application structure evolves to be able to display more projects, without this limit.

Merci pour ta compréhension, je garde un oeil sur ton projet et je te fais signe quand la situation change :)

**Comment by Godefroy** [comment]
Hi @michaelrambeau
Thanks for your answer, I understand!
