### ISSUE TITLE
Add `cross-platform-node-guide`

### ISSUE THREAD

**Issue by ehmicky** [michaelrambeau/bestofjs#231]
Cross-platform Node guide: https://github.com/ehmicky/cross-platform-node-guide

This is guide explaining how to write cross-platform Node.js guide. 

I am not sure whether this fits the "Meta" category, or if you are accepting guides like this at all. Thanks!

**Comment by michaelrambeau** [comment]
Hello again @ehmicky 
Actually there is a section called "Learning resource" where we gather guides, books...

https://bestofjs.org/tags/learning

Would it make sense to add `Cross-platform Node.js Code` in this section?

Thank you for your feedback!

**Comment by ehmicky** [comment]
Yes this would definitely fit.

Do you also accept `awesome` lists such as this one: https://github.com/bcoe/awesome-cross-platform-nodejs? This is a related but different project. `cross-platform-node-guide` is a guide, whereas that second one is a list of tools.

**Comment by michaelrambeau** [comment]
Actually since `Awesome` project itself is already tracked by _Best of JavaScript_ (and it's one of the most popular projects that we tracked, it's often one of the 10 trendiest projects of the day), no other "Awesome" sub-project is included in _Best of JavaScript_.

Otherwise I guess a lot of `Awesome *` projects  should be tracked.

Maybe we could use the "Links" section of the project's page in _Best of JavaScript_, once it's online?
Let me know your thoughts, thank you!

**Comment by ehmicky** [comment]
Yes that makes sense, that's what I assumed as well.
It could be in the Links section indeed :) Thanks!

**Comment by michaelrambeau** [comment]
Hello @ehmicky 
`cross-platform-node-guide` project is available on _Best of JavaScript_, please check here: 

https://bestofjs.org/tags/learning

Thank you for your feedback!

**Comment by ehmicky** [comment]
Thanks!
