### ISSUE TITLE
suggestion to add: Dark Mode Switch

### ISSUE THREAD

**Issue by coliff** [michaelrambeau/bestofjs#257]
**Dark Mode Switch**

Add a dark-mode theme toggle with a Bootstrap Custom Switch.

- Uses local storage to save preference
- Only 230 Bytes minified and gzipped!
- Demo: https://coliff.github.io/dark-mode-switch/index.html

https://github.com/coliff/dark-mode-switch

**Comment by michaelrambeau** [comment]
Hello Christian @coliff 
Thank you for the suggestion, `Dark Mode Switch` will be available on _Best of JavaScript_ very soon.
I wonder what is the best way to "tag" it.

Since it's related to Bootstrap, given the facts that Bootstrap is a kind of "standard" and we have several other projects related to Bootstrap, maybe we could create a tag called "Bootstrap", what do you think?

It would be a bit like we have "React", "Vue", "Angular", "Express" and "Meteor" (the other "special" projects that have their own tag in _Best of JavaScript_).

Thank you for your feedback!

**Comment by coliff** [comment]
Hi Michael. Pleased to hear it will be added! Yes, I think a 'bootstrap' tag would be a great idea. It's the most popular CSS/JS library and there are many great 3rd party add-ons for it.

**Comment by michaelrambeau** [comment]
Hello Christian @coliff
`Dark Mode Switch` is tracked by Best of JavaScript but will show up only when it reaches the threshold of 50 stars on GitHub, sorry, I forgot to mention that point.

As you suggested, an issue template has been added to mention the "requirements".

Also, a new category has been created: https://bestofjs.org/tags/bootstrap

Thank you again for your feedback!

**Comment by michaelrambeau** [comment]
Hello @coliff 
_Dark Mode Switch_ is available on _Best of JavaScript_, congratulations!

**Comment by coliff** [comment]
awesome :-) thanks.
FYI: The link to 'Weekly Best of JavaScript' on the https://bestofjs.org/ homepage is going to an old issue from October.
I guess it should link to https://weekly.bestofjs.org/latest instead

**Comment by michaelrambeau** [comment]
@coliff Thank you very much for the feedback Christian.

The home page has just been updated.

Like we said on Slack, I'm thinking about the idea of a badge _Featured on Best of JavaScript_ to be used by the projects we track.

![image](https://user-images.githubusercontent.com/5546996/69502951-13167900-0f58-11ea-8dbc-1abfd138b484.png)
