### ISSUE TITLE
Add `facebook/flow` project

### ISSUE THREAD

**Issue by dimamo5** [michaelrambeau/bestofjs#26]
https://github.com/facebook/flow
Static type checker for JavaScript

**Comment by michaelrambeau** [comment]
Hello @dimamo5 ,
Thank you, I have added `flow` project, it will be online in 48 hours because the application needs 2 daily snapshots of Github stars to show tendencies.

I was not quite sure about the most appropriate tag to classify the project so I chose `Compilers` (TypeScript project is in this category too)
Be patient!

**Comment by michaelrambeau** [comment]
Hello @dimamo5 , it's online, check here http://bestof.js.org/tags/compiler, thank you!
