### ISSUE TITLE
Add Type-R Library 

### ISSUE THREAD

**Issue by kkilictepe** [michaelrambeau/bestofjs#263]
https://github.com/VoliJS/Type-R

One of the best state management library.
Documentation : https://volijs.github.io/Type-R/

**Comment by michaelrambeau** [comment]
Hello Kenan @kkilictepe
Thank you for the suggestion. 
It's confusing because the documentation you mentioned is linked to the following repo:

- https://github.com/Volicon/Type-R
- which is a fork of https://github.com/VoliJS/Type-R (!)
- which in turn is a fork of https://github.com/gaperton/Type-R (!!)

Which one is the right one? I guess it's the second one (which is the first link you provided), it has 44 stars but the documentation site should be fixed.

In addition, as mentioned in the [issue template](https://github.com/michaelrambeau/bestofjs/issues/new?assignees=&labels=&template=add-a-project-to-best-of-javascript.md&title=) only projects with more than 50 stars are shown, for now.

Thank for your understanding!

**Comment by kkilictepe** [comment]
Hi Michael,
You are right. The second one [https://github.com/VoliJS/Type-R](url)  is the correct one.
I also use this one.
I know that this project has only 44 stars but I`ve been using it for about 3-4 months and I think this project deserves to mentioned here as its features are one of the best i have ever used.

I will try to contact to original developer for fixing the documentation.
