### ISSUE TITLE
Add `analytics`

### ISSUE THREAD

**Issue by DavidWells** [michaelrambeau/bestofjs#269]
Thanks for the awesome site & consideration! 

---

[analytics](https://www.npmjs.com/package/analytics) is a lightweight, extendable analytics library designed to work with any third-party analytics provider to track page views, custom events, & identify users.

Repo: https://github.com/davidwells/analytics
Docs: https://getanalytics.io/

Tags: Analytics, Utils, Redux, browser-storage

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello David @DavidWells 
Thank you for the recommendation, `Analytics` will be available on Best of JavaScript very soon.

We need a new tag called `Analytics` indeed, it would be more appropriate than the very generic `Utils` tag.

**Comment by michaelrambeau** [comment]
Hello David @DavidWells 
A new tag has been added to _Best of JavaScript_:
https://bestofjs.org/tags/analytics

Could you please check?
Also, the project called `Autotrack` has been added (otherwise your project would be alone in its category!).

![image](https://user-images.githubusercontent.com/5546996/64069529-0e5a6580-cc86-11e9-9847-bb5287b60ed3.png)

Let me know if it makes sense, thank you in advance for your feedback.

**Comment by DavidWells** [comment]
Looks great! 

Thanks
