### ISSUE TITLE
github.com/victorqribeiro/radialMenu

### ISSUE THREAD

**Issue by victorqribeiro** [michaelrambeau/bestofjs#270]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [ ] The project is related to the web platform and/or Node.js
- [ ] The project has more than 50 stars on GitHub
- [ ] The project has a thorough documentation
- [ ] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Victor @victorqribeiro 
Thank you for the recommendation.
I've never heard of _radial menu_ before, this is why I wanted to check the demo... but it seems to be offline!

Is it the same kind of menu we can see here: https://wheelnavjs.softwaretailoring.net/ ? (for example, I've just picked the first project I've found on GitHub)

Just a suggestion from a newbie: maybe you could introduce the concept of _radial menu_ (what it is, what are the other open source alternatives...) in the README.md

Thank you for your attention!

**Comment by victorqribeiro** [comment]
My hosting provider sometimes let me down like that. That's why I have an alternative link:

https://victorqribeiro.github.io/radialMenu/

**Comment by michaelrambeau** [comment]
Hello Victor @victorqribeiro 
Thank you for the second link, it works.

It's just a suggestion but I think the project on GitHub should only include the link that works (to GitHub pages) because having a potential dead link has a very bad impact.

I've seen you have closed the issue, I suppose it's because you want to improve the documentation before submitting the project?

As I said before, it would be great to hear more about _Radial menu_ in your project's documentation.

Anyway, thank you again for having introducing the concept of Radial menu to me!

**Comment by victorqribeiro** [comment]
I'll do that as soon as I can

**Comment by victorqribeiro** [comment]
Done!

**Comment by michaelrambeau** [comment]
Thank you Victor @victorqribeiro 
`Radial Menu` will be available on _Best of JavaScript_ very soon.

The documentation still mentions the dead link, I think you should only include the link to the demo hosted on GitHub pages because nothing is more frustrating than opening a dead link.

But it's just a friendly advice 😄

**Comment by victorqribeiro** [comment]
is the link still dead for you? cause it's not for me. it is my website, It did went down for a few minutes the other day for maintenance, but it's back now

**Comment by michaelrambeau** [comment]
Hello Victor @victorqribeiro 
I don't know if it's technically down but every time I check it's slow and I give up after a few seconds because it makes me crazy to wait for a simple demo.
As I told you, the effect on people checking your project is not good, just the fact that you mention an "alternative link" gives the impression that the project is not actively maintained.

As a developer, how would you react if you find a GitHub README.md that says: "if the following link does not work, try this one". Would you trust such a project?

Anyway, it's just a suggestion to help you promote your project.
I care about _Best of JavaScript_ users and I don't want them to find broken links, it would break my heart! 💔 
And I don't want to create a script that checks the dead links in the README.md 😄 !

So, once again, it would be great if you include only the link to the demo hosted on GitHub pages (GitHub pages are both super fast and reliable, don't worry!)

Meanwhile, _Radial Menu_ has been added to _Best of JavaScript_ 🎉 , you can check here: https://bestofjs.org/tags/nav

I will improve the tagging, a tag simply called `Menu` would be better I think.

Thank you for your attention!

**Comment by michaelrambeau** [comment]
Hello Victor @victorqribeiro 

I promised I'd improve the tagging: there is a new tag called `Menu` for projects like yours.

Could you please check here: https://bestofjs.org/tags/menu

Thank you in advance for your feedback!

**Comment by victorqribeiro** [comment]
thank you for helping me getting some visibility to my project
