### ISSUE TITLE
Add @panva/jose

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#272]
> "JSON Web Almost Everything" - JWA, JWS, JWE, JWK, JWT, JWKS for Node.js with minimal dependencies

https://github.com/panva/jose

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello again Filip @panva
Thank you for that recommandatiion too.
`JOSE` project will be available on _Best of JavaScript_ very soon.

**Comment by panva** [comment]
Thanks @michaelrambeau please note the name of the project is `@panva/jose` - its a scoped public package on npm.

**Comment by michaelrambeau** [comment]
OK Filip @panva I see, usually projects tracked by _Best of JavaScript_ have a short name (you could call it the "branding" name) displayed on list and project details pages, that is different from the package name (whether it's scoped or not).

But in the case of your project, we will make an exception and simply call it `@panva/jose`, understood!

**Comment by panva** [comment]
I didn't mean to make it sound like that's what you gotta do :) just wanted to point out something that might have gotten missed.

**Comment by michaelrambeau** [comment]
No problem at all @panva , thank you for having corrected me, `JOSE` would have not made sense at all.

Usually when people submit a new project, I always ask myself: how this project would be called, which name makes the most sense, should the first letter be capitalized or not?

The reason: _Best of JavaScript_ does not track only NPM packages but also some projects about documentation, learning resource... Or sometimes it's just JS code that is not published on NPM.

**Comment by michaelrambeau** [comment]
Hello again Filip @panva 
`@panva/jose` project is available on _Best of JavaScript_.
Could you please check again?
https://bestofjs.org/tags/auth

You may have to reload your browser because there was a bug related to the `/` in the project name (I told you, your project is special 😄 ) and a new version of _Best of JavaScript_ has been deployed.

Thank you for your feedback!

**Comment by panva** [comment]
@michaelrambeau all good. A bit of feedback, why don't you use the tags from published npm modules as well for search?

**Comment by michaelrambeau** [comment]
Hello Filip @panva 
You're right, right now all tags have been manually created and assigned to the projects tracked by _Best of JavaScript_, so they are very generic (like "Authentication" for your 3 libraries).

It could be improved by using the tags assigned to packages in NPM (and the tags in GitHub) too. Maybe they would need to be somehow filtered because sometimes they don't feel very appropriate.

Right now we (open source maintainers always say "we" instead of "I"!) are working on improving the search engine to be able to find projects by picking one or several tags.
Once it's done we will improve the tagging itself and I will ask you for feedback again.

Thank you very much for your ideas!

**Comment by panva** [comment]
My point was to have the tags from package.json be an input for the search function, not necessarily to have them exposed as the bestofjs tags automatically

**Comment by michaelrambeau** [comment]
OK @panva I see what you mean, it would be easier to find what you're looking for if the search engine could process the tags from NPM (in addition of the _Best of JavaScript_ tags that are actually similar to "categories").

Thank you for your time!

**Comment by panva** [comment]
> OK @panva I see what you mean, it would be easier to find what you're looking for if the search engine could process the tags from NPM (in addition of the _Best of JavaScript_ tags that are actually similar to "categories").
> 
> Thank you for your time!

exactly
