### ISSUE TITLE
Add teachcode to the list

### ISSUE THREAD

**Issue by open-source-explorer** [michaelrambeau/bestofjs#294]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

[teachcode](https://github.com/madlabsinc/teachcode) is a great tool which offers a much different learning experience where in which the user can brush up the syntax of his/her programming language of choice.

[Docs](https://teachcode.madlabs.xyz/)

[Twitter handle](https://twitter.com/teachcode_cli)

**Comment by michaelrambeau** [comment]
Hello @open-source-explorer 
Thank you for the suggestion.
It's interesting but I don't know how such a project could be tagged, because it's not really a "learning" resource like the other projects that belong to the "Learning" tag: https://bestofjs.org/projects?tags=learning

If I understand well, it's more a coding challenge that you can run from the command line that lets you submit what you have coded on your computer?

The documentation mentions that a GitHub account is required, it would be nice to explain exactly why.

About the documentation, the only way to access the main page https://teachcode.madlabs.xyz/guide/ is to click on the "Get started" button from the top page but the page is not available from the left sidebar, which is little weird (but I may have missed something).

**Comment by open-source-explorer** [comment]
GitHub account is made use as a platform to track the user's progress. I would say do take it for a spin and you can see it for yourself. Regarding the docs, yeah might be fixed later on.

**Comment by open-source-explorer** [comment]
@michaelrambeau friendly ping.

**Comment by michaelrambeau** [comment]
Hello @open-source-explorer , happy new year!
Thank you for your "friendly ping" (I never got a friendly ping before 😄), I checked again and I cannot see any clear information added about why the user needs to enter the GitHub credentials? Sorry to ask again, but it's a bit scary, to me, think about a user who never heard about your project before.

And it does not seem you solved the navigation problem I mentioned?

Also, you should provide an example of the challenge the user has to solve, showing the first one for example, it would help to understand what the project is about.

And the last point, how would we tag such a projects in _Best of JavaScript_ (that was my initial question)?

Thank you again for your understanding, and let me know when these points are improved.
And sorry if it requires time and work, I also know how much maintaining open-source projects can be exhausting, good luck!
