### ISSUE TITLE
[Recommendation] docx

### ISSUE THREAD

**Issue by dolanmiu** [michaelrambeau/bestofjs#295]
Hi, I am the author of docx: https://github.com/dolanmiu/docx

> Easily generate .docx files with JS/TS with a nice declarative API. Works for Node and on the Browser.

I would love for this project to be featured

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Dolan @dolanmiu 
Thank you for the recommendation, _Docx_ project will be available on _Best of JavaScript_ very soon.
Among the existing tags, I can't see any tag that would be appropriate.
I could create a `docx` tag but there would only one project... Any suggestion, an idea about something more generic? 
Thank you for your help!

**Comment by dolanmiu** [comment]
Tags:

Angular - it can be used in Angular
XML - Pro tip: Word documents are essentially `xml` files, zipped, then renamed with the `.docx` extention
Vue - Can be used in Vue too
Documentation
Presentation
Utils

**Comment by michaelrambeau** [comment]
Hello @dolanmiu 
It's available under the tags `XML` and `Documentation`, as you said, please check here: https://bestofjs.org/projects/docx

I think Angular and Vue.js are not really appropriate tag in the context of _Best of JavaScript_ because `docx` does not provide integration or components specific to these frameworks, unless I missed something.

And `utils` is usually a bad tag I use when I'm not inspired at all 😆 , or for libraries that look like "swiss-army knives" for very common tasks.

Thank you for your understanding, any feedback is welcome!

**Comment by dolanmiu** [comment]
Thanks so much, can close this
