### ISSUE TITLE
Add Function-tree

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#297]
npm package page: https://www.npmjs.com/package/function-tree
Repository: https://github.com/cerebral/cerebral/tree/master/packages/node_modules/function-tree

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Denis! @gamtiq 
Actually the GitHub project is already tracked by _Best of JavaScript_ as you can see here: https://bestofjs.org/projects/cerebral
However it's the main package we track, the one called `cerebral`, not `function-tree`.
It means that we may need a way to show properly these mono-repos that include several packages, in the future?

**Comment by gamtiq** [comment]
Hello Michael!
Indeed `function-tree` is a part of `cerebral` repository. But it is independent and helpful package by itself (`function-tree` can be used without `cerebral` at all).
IMHO it would be very useful to have ability to add and show such packages in _Best of JavaScript_.

**Comment by michaelrambeau** [comment]
Thank you for the feedback Denis @gamtiq 
For mono-repos that include several packages, instead of a section called `package`, it should be `packages` (with a final `s`) and it would it display information for each package.
Maybe we could be using tabs to avoid making the page too heavy (visually).

By the way, what do you think of the latest changes in _Best of JavaScript_:

- the new search engine: https://github.com/bestofjs/bestofjs-webui/issues/75
- the graph about the monthly trends: https://github.com/bestofjs/bestofjs-webui/issues/81

There are 2 priorities now:

- Improve the home page to make it more attractive / interesting and help people discover projects without using the search engine
- Show a graph about the variation of the number of dowloads by month: https://github.com/bestofjs/bestofjs-webui/issues/78

Once it's done, let's do this "mono-repo" feature, I will create an issue.

**Comment by gamtiq** [comment]
Michael,
Thank you for your excellent work!

> By the way, what do you think of the latest changes in Best of JavaScript:

Both features are useful.

> Show a graph about the variation of the number of dowloads by month

I suppose that feature can be helpful when selecting a package for a project.

Regarding
> help people discover projects without using the search engine

One feature that I miss is a separate page with all tags.
The previous version of _Best of JavaScript_ had a sidebar that listed all available tags.
Now set of available tags is only accessible by drop-down list which sometimes is not convenient (not user-friendly).
I suppose the separate page with all available tags-links (and perhaps some additional data/stats for each tag) would be helpful.

**Comment by michaelrambeau** [comment]
OK Denis @gamtiq restoring the full list of tags, that should the priority number 1!

What do you think, we could add an entry in the top navigation bar, the navigation menu could have 3 entries:

All Projects  | All Tags | Hall of Fame

**Comment by gamtiq** [comment]
Michael,
I suppose it would be great to add _All Tags_ into the top navigation bar, as you proposed.
