### ISSUE TITLE
antv projects

### ISSUE THREAD

**Issue by afc163** [michaelrambeau/bestofjs#298]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

---

- https://github.com/antvis/g2plot
- https://github.com/antvis/g6
- https://github.com/antvis/f2
- https://github.com/antvis/l7
- https://github.com/antvis/graphin
- https://github.com/antvis/g

**Comment by michaelrambeau** [comment]
Hello @afc163 
Thank you for the recommendations.

I think the following projects are already in _Best of JavaScript_:

- G2
- F2
- F6

Check here: https://bestofjs.org/projects?query=antvis

![image](https://user-images.githubusercontent.com/5546996/70835910-e8765c80-1e41-11ea-9c22-7f1181477360.png)

About `G` projects it does not seem that the documentation is in English? https://g.antv.vision/en/docs/guide/introduce

So the 3 following projects will be added:

- `G2Plot`
- `L7`
- `Graphin`

**Comment by michaelrambeau** [comment]
Hello @afc163 
It's online, could you please check?
If you search for `antivis` you will find 6 projects!
https://bestofjs.org/projects?query=antvis

By the way, do you think a Chinese version (hosted on a "mirror"?) of _Best of JavaScript_ would be a good idea? I've been told that the application is slow from China, because of connectivity problems.
Thank you!
