### ISSUE TITLE
Add Playwright

### ISSUE THREAD

**Issue by d-akara** [michaelrambeau/bestofjs#320]
https://github.com/microsoft/playwright

**Comment by michaelrambeau** [comment]
Hello Chad @dakaraphi 
Thank you for the suggestion.
_Playwright_ is already tracked by _Best of JavaScript_.
I wonder why you were not able to find it?
Any feedback to improve the search feature is welcome, thank you in advance!

https://bestofjs.org/projects?tags=auto

![image](https://user-images.githubusercontent.com/5546996/80542473-fa6b2d00-89e7-11ea-8e59-dbb4f18a36cd.png)

**Comment by d-akara** [comment]
I don't find it when searching.
![image](https://user-images.githubusercontent.com/10656375/80551162-90736900-8990-11ea-83d2-6fc689e26b2b.png)

**Comment by michaelrambeau** [comment]
Thank you Chad @dakaraphi 
From your screenshot you are using the old URL `bestof.js.org` instead of https://bestofjs.org/
I don't understand why you are not redirected to: https://bestofjs.org/ because I'm redirected if I try to access the previous domain.
Can you confirm the URL you are using in your browser?
Have you any idea why you are not redirecred, is there something I should do?
At least I could upload a page saying that the site has moved if no redirect is possible... but I'd like to be able to check the old URL by myself too...

**Comment by d-akara** [comment]
So I had a bookmark for this URL:
http://bestof.js.org/projects/trending/today

**Comment by michaelrambeau** [comment]
Thank you for the feedback Chad @dakaraphi 
So it seems there is a correct redirect if you go to the root URL `bestof.js.org` but no redirect if you go to any existing page `bestof.js.org/*` (like the one you bookmarked).

I will upload a page with a message asking to update the bookmark, since I cannot handle the redirect rules on `js.org` domain. Let me know if you have a better idea, thank you in advance!

**Comment by michaelrambeau** [comment]
Hello again Chad @dakaraphi 
I set up a static HTML page on the previous domain to ask users to update their bookmarks.
Could you check again?

![image](https://user-images.githubusercontent.com/5546996/80593107-8a968a00-8a5b-11ea-97d7-fe9af1291b3f.png)

By the way, since you were using the "old version" of _Best of JavaScript_ until today, I'm curious to know your feedback about the current version.
Thank you in advance!

**Comment by d-akara** [comment]
Yes, I now get the 'moved' page posted above.
It looks good, I like the sorting options.

BTW, There is one additional sorting option I would really like.  That would be 'sort by project creation date'.

**Comment by michaelrambeau** [comment]
OK thank you Chad @dakaraphi , I will let you know if I can add that sorting option.

That would mean adding more data to big JSON file loaded when the application starts but I'm thinking about a more flexible architecture.

**Comment by michaelrambeau** [comment]
Hello @dakaraphi 
Sorry for the delay, I've just added a feature to be able to sort projects by date of creation.
What is missing, I think, is the ability to see this data from the project list (now you have to open the project details page to see it).
Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/87238007-fcb22480-c437-11ea-8f28-64f13cfe26bc.png)

**Comment by d-akara** [comment]
@michaelrambeau Thanks!
