### ISSUE TITLE
Add React-Virtual

### ISSUE THREAD

**Issue by tannerlinsley** [michaelrambeau/bestofjs#323]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

react, virtualization, performance, windowing

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
It's good to see you again!
OK _React Virtual_ will be available very soon!

_Best of JavaScript_ changed a lot since last time you reached us:
- a new search engine has been introduced to let users mix one or several tags and keywords to combine search by tags and full-text search (https://github.com/bestofjs/bestofjs-webui/issues/75)
- We tried to make the home page more attractive, mode dynamic, adding s slider with some featured projects, for example (https://github.com/bestofjs/bestofjs-webui/issues/86)

I'm curious what you think about these change and how we could make _Best of JavaScript_ more useful for you, your feedback would be very valuable to us!

Also, I noticed _React Query_ was super hot recently, I'd like to promote it as a "featured project" but I need a SVG version of the logo (without the wording, see below), is it possible?

![image](https://user-images.githubusercontent.com/5546996/81488698-3e431980-92a7-11ea-9398-0ea17002f147.png)

Thank you in advance!

**Comment by tannerlinsley** [comment]
Yeah I can get you that. It’ll be a few days til I get to it. Don’t wait up!

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
It's online!
An other question: since you have several hot projects (3 projects on _Best of JavaScript_, see the screenshot) what if we provided a badge _"Featured on Best of JS / + XX stars this week_" to be included in the README.md (this issue https://github.com/bestofjs/bestofjs-webui/issues/79), would it be useful?
This way you could see at a glance if a project is hot/cold, right from GitHub.

Sorry for all my questions, I'm waiting for your feedback, thank you in advance!

![image](https://user-images.githubusercontent.com/5546996/81615173-1f19c880-941c-11ea-93cd-1b6e4cdef84a.png)

**Comment by tannerlinsley** [comment]
I would love that. In fact, I would love a badge with the daily count and rank or something like that. Could be cool?

**Comment by michaelrambeau** [comment]
@tannerlinsley Maybe we could provide different variations, for example

- `Best of JS | +10 stars today`
- `Best of JS | +45 stars this week`
- `Best of JS | +450 stars this month`

The background color could be one of the colors used in the heatmap: blue when it's cold, yellow, orange purple as it becomes "hotter"...

An other possibility is a badge that opens a given "tag" in Best of JS:

- `Best of JS | Data fetching` for React Query
- `Best of JS | Table` for React Table

Thank you for your ideas (and no rush about my previous questions!)

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley !
Sorry for the delay but I've just prepared the badge for `React Virtual` project:

[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=tannerlinsley%2Freact-virtual%26since=weekly)](https://bestofjs.org/projects/react-virtual)

[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=tannerlinsley%2Freact-virtual%26since=daily)](https://bestofjs.org/projects/react-virtual)

What do you think, is one these 2 badges good enough to be included in your README.md?

Thank you for your feedback!

**Comment by tannerlinsley** [comment]
Looks great! Hire often do they update?

**Comment by michaelrambeau** [comment]
Data is updated every day at 6:00 AM Japan time (3 PM in Utah).

It's the same data that powers https://bestofjs.org/ of course.

**Comment by tannerlinsley** [comment]
Cool. I honestly wish BOJS updated every hour. I would keep it open all day.

**Comment by michaelrambeau** [comment]
Thank you for having checked Tanner @tannerlinsley 
Here is the snippet for React Query project:

```md
[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=tannerlinsley%2Freact-query%26since=daily)](https://bestofjs.org/projects/react-query)
```

which should render this:

[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=tannerlinsley%2Freact-query%26since=daily)](https://bestofjs.org/projects/react-query)

Can I make a PR in your repo to include it in the README? If you think it's valuable information of course, I don't want to be too pushy, this is why I'm asking you here first.

**Comment by tannerlinsley** [comment]
Yeah go for it!

**Comment by michaelrambeau** [comment]
Hello again @tannerlinsley 
React Query was the most popular project of the week, congratulations!
I send a newsletter every week.
I wrote this for _React Query_: https://weekly.bestofjs.org/issues/109
Before I send the newletter (2500 recipients, opened by 35%~40% of the recipients on average), could you check if the content is OK?
Thank you again!

**Comment by tannerlinsley** [comment]
Looks good! Double check the section in the readme about differences between RQ and SWR

**Comment by michaelrambeau** [comment]
Thank you @tannerlinsley 
I've sent the newsletter but I didn't want to enter too much in details, writing this newsletter already takes too much time from me 😅 .

Also thank you very much for having starred _Best of JS_ last week, a lot of your followers "followed" your move and last Wednesday was by far the most prolific day! (+47 stars)
