### ISSUE TITLE
JS Service Wrapper

### ISSUE THREAD

**Issue by behnamazimi** [michaelrambeau/bestofjs#331]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

- service-wrapper 
- service-queue 
- request-queue

Project: [**js-service-wrapper**](https://github.com/behnamazimi/js-service-wrapper)

**Comment by michaelrambeau** [comment]
@behnamazimi Hello Benham,
Thank you for the suggestion, the project looks great but unfortunately _Best of JS_ only tracks projects with more than 50 stars, this threshold exists mainly to avoid requests about low-quality projects.
This threshold may change in the future when a new architecture is implemented: now _Best of JS_ is a SPA that loads all data from a single JSON file that contains more than 1500 projects, which limits the total number of projects we can show.
Things should be more flexible!

I know you think it's unfair because all projects start with very a few stargazers but we are keeping an eye on your project, and I will contact you when things change.
Thank you for your understanding!
