### ISSUE TITLE
Add `NaturalIntelligence/Stubmatic` project

### ISSUE THREAD

**Issue by amitguptagwl** [michaelrambeau/bestofjs#34]
https://github.com/NaturalIntelligence/Stubmatic
A stub server to mock behaviour of HTTP(s) / REST / SOAP services

**Comment by michaelrambeau** [comment]
Hello @amitguptagwl , thank you for the suggestion.
It seems that you put a lot of work in this project.

The website mentions

> No bug reported yet (from Apr 2016 to till date)

...because there is no 'issue' at all in the Github repository. But an *issue* in Github can be any *discussion* or *request* related to to your project, so having "no issue at all" is not really a good thing, I think.

An other thing, the web site mentions:

> There are more than 3000 people around the world who is using this tool.

![image](https://cloud.githubusercontent.com/assets/5546996/21597559/bc47be80-d18f-11e6-800b-d7d15b88eb8e.png)

...is it true ? It looks like a marketing argument ;)

Because I don't think a repo with one star and no issue at all can be used by so many people. But I can be wrong, it's only my point of view.

Thank you in advance for your comments, it's great to see people working hard and submitting their projects!

**Comment by amitguptagwl** [comment]
Hello @michaelrambeau !! First of all thanks for detailed attention.

Stubmatic is renamed from my old repo [StubbyDB](https://github.com/NaturalIntelligence/StubbyDB). Stubby DB is an old repo. As it's name was a bit confusing, I decided to rename it. You can check the stats on it's github page or [here](http://www.npm-stats.com/~packages/stubby-db). I mentioned 3000 on the basis of these stats. However I believe it should be more than that.

Since there is no issue reported for Stubby DB in last 9 months, I mentioned it as "No bug reported yet". But this is true that the issues reported in github can be for discussion, feature request, general enquiry or something else. But in case of bug they'll also be reported there. What I meant by that statement is that I'm active to maintain that repo. However, I believe, I should change that statement to "No open bug" :-)

**Comment by michaelrambeau** [comment]
Hello again Amit,
OK I am adding your project, under the tag `Testing tools`.
As I told you, I have seen that you worked a lot, and I know how much it takes time and energy to create and maintain one's own project.
It will be online in 48 hours, be patient!

**Comment by amitguptagwl** [comment]
Great.. Thanks for your appreciation

**Comment by michaelrambeau** [comment]
It's online, check here: http://bestof.js.org/tags/test.

**Comment by amitguptagwl** [comment]
Thanks a lot for update. I believe npms% & packagequality% will take sometime to update

Is there any possibility to link to custom [logo]?(https://naturalintelligence.github.io/Stubmatic/img/stubmatic_logo.png)

**Comment by michaelrambeau** [comment]
The npms.io score will be updated in a few hours, sorry for the delay.

About the logo, it's the **repo owner's** logo that is automatically displayed.

* So why not update 'NaturalIntelligence' avatar with that logo ?
* Or, if it's not possible, why not create a specific Github org for that project ? (The project would become `stubmatic-org/stubmatic` for example, instead of 'NaturalIntelligence/Stubmatic')

**Comment by amitguptagwl** [comment]
Thanks for your response. NP for the counts

I was thinking to put all my mazor work under NI repo, and small work under my user id directly. In this case, all the repo under NI will have same logo as NI logo. So I was wondering if we can have some logic like

> project repo has logo.icon|logo.png|etc then take it from there otherwise take from repo owner's logo

just a feature request :)
Otherwise it's fine what we have. 

Thanks

**Comment by michaelrambeau** [comment]
Good morning Amit,
The npms.io score has been updated and you got 2 more stars, good job!

![image](https://cloud.githubusercontent.com/assets/5546996/21699849/da59c00a-d3e0-11e6-9e7b-f6a35cbd5f43.png)

About the logo, I think your idea is good, I will work this weekend to find a way to set a specific logo URL for a given project, stay tuned!

I appreciate the fact that your logo filesize is small (1.5 KB from DevTools), thank you!

**Comment by amitguptagwl** [comment]
Thanks @michaelrambeau
