### ISSUE TITLE
The GraphQL Guide

### ISSUE THREAD

**Issue by lorensr** [michaelrambeau/bestofjs#386]
Book site: https://graphql.guide/
React tutorial code w/ 110 stars: https://github.com/GraphQLGuide/guide
Book source: https://github.com/GraphQLGuide/book

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Learning resource
GraphQL 
React
Testing
Vue
React Native

**Comment by michaelrambeau** [comment]
Hello Loren @lorensr 
Thank you for the suggestion.
We have a "book" section in _Best of JS_ https://bestofjs.org/projects?tags=book but it's about books you can read "for free" since _Best of JS_ does not promote any paid content (in principle, sometimes the boundary is blurry!) and it does not seem the content of the "The GraphQL Guide" book is accessible?
(well I'm not sure, the `GraphQLGuide/book` repo seems to be a Gatsby application but it's not a repo you can browse in order to read the book, I think?)

![image](https://user-images.githubusercontent.com/5546996/114634836-5ebcf480-9cfe-11eb-8206-92ceed4e7f14.png)

Regarding the other repo `GraphQLGuide/guide`, you said it's a tutorial but the `master` branch shows only 2 files and the README.md does not seem to explain how it work (I guess you have to switch branches and consider each branch as a standalone app that illustrates a chapter but where are the explanations?)

Sorry for my very poor understanding, I may have missed something very obvious!
Thank you in advance for your explanations!

**Comment by lorensr** [comment]
Yes, the content of the book is freely accessible. You can browse the repo (`text/` directory) to read the book: https://github.com/GraphQLGuide/book/blob/master/text/SUMMARY.md

It includes the explanations for each step of the `GraphQLGuide/guide` tutorial: https://github.com/GraphQLGuide/book/blob/master/text/react/index.md

Starting with step 0: https://github.com/GraphQLGuide/book/blob/master/text/react/setting-up.md#app-structure

We don't advertise this in the READMEs as we'd prefer for people to purchase it. Up to you as to whether this fits ☺️ Thanks for your consideration!

**Comment by michaelrambeau** [comment]
Hello Loren @lorensr 
Thank you for the explanations.
So it's possible to browse the content online if you know the repo's structure (the `text` folder!) but it's not recommended.
Your request is a dilemma: on one hand I can see you put a lot of effort in the book, I understand your goal, on the other hand, as a basic user, I can't stop thinking: but where is the content, how I'm supposed to find it? Is this _Best of JS_ guy trying to sell me a book rather than sharing content?

To be consistent with the other projects of the category, maybe it's better to wait until your clarify your intentions in the README ("You can browser the content by going here but...")?


Sorry again, I'm open to any suggestion, thank you for your understanding!

**Comment by lorensr** [comment]
No worries, thanks again!
