### ISSUE TITLE
Add spotify-api.js

### ISSUE THREAD

**Issue by scientific-dev** [michaelrambeau/bestofjs#388]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

**Spotify-api.js**

Spotify-api.js is an unofficial type strict spotify api wrapper for node.js which is a beginner friendly and easy to use. 

**Github:** https://github.com/spotify-api/spotify-api.js
**Documentation:** https://spotify-api.js.org

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- API Wrapper / SDK

**Comment by michaelrambeau** [comment]
Hello @Scientific-Guy 
Thank you for the suggestion.
I don't know how `spotify-api.js` could be tagged in _Best of JS_, we don't have a category "API wrapper"... why did you pick "real time" https://bestofjs.org/projects?tags=realtime by the way? 
Is it because there is the project _Discord.js_ inside this category?
I remember I didn't know where to put it and I picked `real time` because it can be used to build real-time chat but now that I'm thinking more, a new category "API Wrapper" would be more appropriate maybe? Can you see a better tag to be created?
Sorry for all those questions and thank you in advance for your help!

**Comment by scientific-dev** [comment]
Yeah i actually feel to add a tag named Wrapper but i could not find good enough tags relating to my project so i just searched projects which are similar to mine most of them had the `real-time` tag so me too has used the tag but i feel adding the tag `Wrapper` or `API Wrapper` will be better

**Comment by michaelrambeau** [comment]
Hello @Scientific-Guy 
It's online, please check here: https://bestofjs.org/projects?tags=api-wrapper
The tag I created is called **"API Wrapper / SDK**", let me know if it makes sense, thank you in advance!

**Comment by scientific-dev** [comment]
Yeah the tag `API Wrapper / SDK` is awesome and will help other users to choose the perfect tag. :)
