### ISSUE TITLE
https://www.imagine.ai

### ISSUE THREAD

**Issue by anusheel** [michaelrambeau/bestofjs#395]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Node.JS framework

**Comment by michaelrambeau** [comment]
Hello @anusheel 
Thank you for the recommendation.
I may miss something obvious but I cannot see the GitHub repository, could you share the link?

**Comment by anusheel** [comment]
https://github.com/imagineai/create-node-app

**Comment by michaelrambeau** [comment]
Hello @anusheel  
Thank you for the link.
Is there a reason the GitHub link does not show up anywhere on the site?
It it because the actual "source" code is developed elsewhere as I can see only one huge commit beside the initial commit (everything else being README.md updates) when I check the commits?
Sorry if I look very curious about the project! 😅 

A small thing about the installation process: the README says it has to be installed globally (`npm install -g`) but with `npx` you don't have to install it globally and the installation could be made simpler, something like `npx create-xxx`.
(npx comes with npm 5.2+ and higher).
So maybe you could mention this way of installing `imagine`?

Thank you in advance for the feedback!

**Comment by L1lith** [comment]
Yeah I was perusing the project and one feature I think could improve the development experience would be generators. Global dependencies can be hefty but one benefit is that you could do something like `imagine generate endpoint {name}`. [Feathers.js](https://feathersjs.com/) is a great example of this as when you wish to create a new service it gives you a configuration walkthrough in the CLI rather than having to implement each new page or endpoint yourself. Perhaps this feature already exists and I missed it.

Another cool feature would be integration for deployment to AWS and other cloud services. Deploying on a VPS is fine in most cases but cloud services can save a lot of money when someone doesn't want to have a server running all the time, or it can also be important when a VPS is unable to handle hosting the service due to intense amount of server load.

Also no pressure but if you like my library [here](https://github.com/L1lith/Sandhands) it might be a good option to provide users for sanitation.

I don't know if this is out of the scope of what you're trying to do with this project, but there doesn't seem to be any front-end integration, this could be a useful feature (even as little as allowing say a local port to be served as the front end might be nice)

Feel free to take these suggestions at your discretion, these are just the things I would personally be looking for in a server template.

**Comment by L1lith** [comment]
@anusheel I'm still interested in hearing your thought on my feedback and hearing more about your vision for your project

**Comment by anusheel** [comment]
@L1lith sorry I missed this. Thanks for all the awesome suggestions. Good idea re: the endpoint generator. We actually had a command line (still do) but then built a UI to make it easier for people to use the tool.
Will look into Sandheads for sanitation - do you support both frontend and backend? 
Happy to discuss more - feel free to ping me at anusheel@imagine.ai or calendly.com/anusheel and we can setup a time to discuss.

Thanks,
Anusheel
