### ISSUE TITLE
Fix the Discord

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#398]
@michaelrambeau 
I know it's probably more than you like to deal with, if you'd like I could either create a new server or revamp the old one? I'm familiar with discord permissioning and adding moderation bots so something like that could help filter out the spam. Also we could make the server whitelist only to prevent spam.
 
I think I initially misread your response in the canvacord thread and thought you meant like being a dictator regarding uploading projects. Taking immediate action in a discord server I do not think is uncalled for in any way, and having a discord server is a privilege and should ideally exist primarily for the team's communication so if people are going to spam it we definitely could use a whitelist.

**Comment by michaelrambeau** [comment]
Hello @L1lith 
Thank you again for your help, I appreciate your efforts to help us build a better _Best of JS_.
Yes I think there was a misunderstanding in the other thread, I know that you didn't invite your friends, I was talking to the scientific guy, no worries 😄 !
Can you join https://discord.gg/J8GWzSa7 and I will give you the rights (or at least we could discuss more directly?)
Can you tell me in a few words how the whitelist concept works?
We have already a Slack team that works with a kind of white list since the access is restricted to only some people who were invited, is it the same concept?
In my mind, I wanted to have an open space that anyone can join, like the Discord server for https://chakra-ui.com/ project for example.

**Comment by L1lith** [comment]
@michaelrambeau basically you can create one time invite links. Another alternative though would just be to assign all of the contributers a staff only role or something like that, and we can make some staff only channels, as well as having public channels so people can talk about the project or ask for help.
[Discord - How do I setup Permissions?](https://support.discord.com/hc/en-us/articles/206029707-How-do-I-set-up-Permissions-)
