### ISSUE TITLE
Add Universal Test Cases (per tag)

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#400]
It would be cool if there was a set of "universal test cases" where libraries could implement a standardized test (each test might say be tailored to the tag like data sanitation) then libraries could link an implementation of it, then users could compare the libraries based on how clean their syntax is to implement the solution, and also the performance of the library itself on the task

**Comment by michaelrambeau** [comment]
Sorry for the late comment @L1lith , I've replied to you in Discord but I forgot to update this thread!

I said this in Discord:

> That looks like a very ambitious project! That would mean defining a minimum "requirement" for some tags (about the tasks that are supposed to perform the libraries)?

Because currently _Best of JS_ is not a really a tool to evaluates new projects based on automatic processes and requirements. It's more a tool that aggregates and classifies projects related to some metrics.

The amount of projects we can display in the current UI is quite limited because of the architecture of the application this is why my focus for 2021 is to try to move to a different architecture that would allow more flexibility (see this [roadmap](https://github.com/bestofjs/bestofjs-webui/issues/109)). 

But if you have any idea about how we could implement such generic tests, please feel free to make any suggestion, it could be helpful when we evaluate new "candidates".
