### ISSUE TITLE
Change the daily rankings to reduce odds of duplicate listings

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#401]
I think the daily rankings could be reworked so that it rewards "surges" in the number of stars added. For example a giant project with a lot of stars will likely gather more stars per day than a smaller one, so receiving 100 stars might actually not be a lot on a given day for project x, but for smaller project y it might have doubled the total number of stars. So comparing the deviation of the star count per day might be an option. Another option might be to set a cooldown or reduce the odds of something being on the hot list if it was already recently posted. 

An example of why this could be an issue is that You don't know JS was elected 4 times in the past week. I haven't used You don't know js, and it's probably awesome, but it might not be interesting to keep giving the same results so frequently.

**Comment by michaelrambeau** [comment]
Thank you very much @L1lith for starting the debate.

When I was sending a weekly newsletter, I was including 2 types of rankings: 

- the absolute numbers (by number of stars added the week)
- and the "relative growth" (% of star added since last week)

because, as you said, some huge projects tend to have a lot of inertia and get a relative steady amount of new stars every day.

It's especially true for the projects of the category "Learning" like the famous book "You don't know JS" or the project about algorithms implemented in JS.

https://bestofjs.org/projects?tags=learning

And this is the reason why I exclude those projects from the "Daily Rankings" section of _Best of JS_ top page ([code here](https://github.com/bestofjs/bestofjs-webui/blob/9b88c8769c4fcc781ae49f2f84188cb80dcd41fd/src/components/home/home-projects.tsx#L19))... but not from the Discord notification, I'm sorry for the confusion, I should be  consistent.

So at first, I'm going to fix the Discord notification to reflect exactly the content displayed on _Best of JS_ top page.
