### ISSUE TITLE
Add Indiepen to Best of JS

### ISSUE THREAD

**Issue by HenrikFricke** [michaelrambeau/bestofjs#402]
Hi 👋

I'd like to propose my first open source project: 

- Website: https://indiepen.tech/
- GitHub: https://github.com/yetanother-blog/indiepen/

Checks:
- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

- Syntax highlighting
- Dev Tool

Thx and have a nice day 🙏

**Comment by michaelrambeau** [comment]
Hello Henrik @HenrikFricke 
Thank you for the suggestion, it will be available on _Best of JS_ very soon!
About the tagging, the tag `Code Editor` might be more appropriate: https://bestofjs.org/projects?tags=code-editor as we have a project called _Pen Editor_ that seems to have a similar scope?
Or maybe in addition of "Syntax Highlighting".

Note: tagging is difficult because concepts often overlap and tags don't have the same level of abstractions, some of them being very generic, some of them being specific, `Syntax Highlighting` being often a feature provided by "Code Editors".

About the "Dev Tool" tag, I created it because I didn't know how to classify the project https://github.com/responsively-org/responsively-app, so to me it means something that enhance the developer experience in the browser like "DevTools" do in Firefox and Chrome but I have to admit it's a very blurry concept... 😅

**Comment by HenrikFricke** [comment]
Hey @michaelrambeau, 

thanks for your quick reply. I like you suggestion, code editor might be also a good fit for Indiepen. To be honest, I tried my best to find the right tags for the project but it's really difficult to break it down and put it into categories. 

I really appreciate your input :)

**Comment by michaelrambeau** [comment]
Thank you for your having found your way through the jungle of the tags Henrik!
Actually your request is helpful because I realized that I "missed" projects that currently have the tag "Syntax Highlighting" but should also have the tag "Code Editor": _Ace_, _Prose Mirror_ and _JSON Editor_.

Everything will be fixed very soon, be patient and have a good end of week!

**Comment by michaelrambeau** [comment]
Hello Henrik @HenrikFricke 
_Indiepen_ is available on Best of JS, please check here for example: https://bestofjs.org/projects?tags=code-editor

**Comment by HenrikFricke** [comment]
Cool, it looks good. Thx for the support! 🙏
