### ISSUE TITLE
Add Awacs to Best of JavaScript

### ISSUE THREAD

**Issue by anonrig** [michaelrambeau/bestofjs#406]
Hi All,

I wanted to share our privacy and security focused user behavior analysis server Awacs. Even though we don't have 100 stars (we're getting there!), I wanted to share it with the community.

 https://github.com/socketkit/awacs

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

Node.js framework, Mobile, Security

**Comment by michaelrambeau** [comment]
Hello Yagiz @anonrig 
Thank you for the recommendation.
I was checking the documentation but I could not find any demo to understand better what can be built with Awacs since I'm not very familiar with the concept of "user behavior server".

Is it somehow similar to one of the projects from the "Analytics" tags? https://bestofjs.org/projects?tags=analytics

Maybe it could be interesting to explain how it compares with existing solutions in the documentation? I suppose the use of gRPC is pretty unique, we could use this tag by they way: https://bestofjs.org/projects?tags=rpc

Sorry for my ignorance, thank you in advance!

**Comment by anonrig** [comment]
Hi @michaelrambeau

Thank you for the response. Awacs is indeed an analytics server particularly for mobile applications. A usage of Awacs can be found on the javascript sdk (https://github.com/socketkit/socketkit-js)

**Comment by L1lith** [comment]
I'm also trying to better understand your library. I believe the main repo is the server application, and the SDK libraries are the client libraries. What doesn't make sense to me is how do we setup the server application? I tried running the server but I ran into [this issue](https://github.com/socketkit/awacs/issues/11). I think there should definitely be more clear instructions on how to get the server running properly.

I also noticed there was no testing on the JS client lib
https://github.com/socketkit/socketkit-js/issues/1

**Comment by anonrig** [comment]
Hi @L1lith 

Easiest way to run Awacs locally is to use Docker-compose. Please follow the following documentation from the Awacs documentation page. https://awacs.socketkit.com/guides/deployment/docker

**Comment by L1lith** [comment]
> Hi @L1lith
> 
> Easiest way to run Awacs locally is to use Docker-compose. Please follow the following documentation from the Awacs documentation page. https://awacs.socketkit.com/guides/deployment/docker

Thanks @anonrig, sorry I've been caught up in my own projects lately so I've been late to respond but when I went to that website the link is broken. Can I get an update on this?

**Comment by anonrig** [comment]
The documentation is currently being re-written, but all of the code is available on Github at https://github.com/socketkit/awacs
