### ISSUE TITLE
Add daisyUI

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#411]
https://daisyui.com

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

`Component Toolkit`, `CSS Toolkit`

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you for the recommendation.
I would tag it only "CSS Toolkit" (like Bootstrap and friends) rather than "Component Toolkit" because component toolkits are sets of components related to a given UI framework (example: Material UI for React), in Best of JS, if you are OK?

I know it's far from being obvious, any suggestion is welcome 😅 
At least I should add the "definition" of the tags somewhere, in the Tags page for example: https://bestofjs.org/tags

**Comment by gamtiq** [comment]
Hello Michael,
I agree that "CSS Toolkit" is more appropriate tag.
I've added "Component Toolkit" because daisyUI is a component library for Tailwind framework. So it fits for your aforementioned definition (sets of components related to a given UI framework). :-)
Of course you are free to set tags that you see are more right.

**Comment by michaelrambeau** [comment]
It's online and it's one of the hottest projects of the day!

Sharing a preview with the Dark Mode I'm working on:

![image](https://user-images.githubusercontent.com/5546996/130303088-6c0b12b1-579e-4456-9d5c-de7be48d4754.png)

**Comment by gamtiq** [comment]
Dark Mode looks nice.
