### ISSUE TITLE
Add Burdy

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#423]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- CMS
- nodejs-framework
- Blog

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat 

Thank you but who is Burdy? 😄 
From the tags you picks I supposed it's https://github.com/burdy-io/burdy am I correct?

The description says "Most advanced open-source Headless CMS built in NodeJS and React"... it's a very bold statement because there are several big contender in the category (Strapi?).
Thank you for the feedback!

**Comment by xeusteerapat** [comment]
Hi,@michaelrambeau

The link you provided is correct, sorry I missed that 😅

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Burdy` is available on _Best of JS_, please check!

CMS tag: https://bestofjs.org/projects?tags=cms
