### ISSUE TITLE
Amazing JS rounting!

### ISSUE THREAD

**Issue by agrublev** [michaelrambeau/bestofjs#425]
https://github.com/agrublev/fc-hash-router

tag: routing

**Comment by michaelrambeau** [comment]
Hello Angel @agrublev 
Thank you for the suggestion.
I was checking the demo on CodeSandbox, adding a route `/products` (in addition of the existing one `/products/:firstVar/:...`) to simulate the common pattern of nested routes but it didn't work as expected.
Maybe you could update the example and the documentation to reflect some common patterns?

Also I wonder what is the motivation behind the project, why one's would use a hash router rather than the browser history, since static hosting solutions like Surge.sh or Netlify usually provide solutions to handle routing in the browser for SPAs?
Usually routing library provide an abstraction that let users switch between the browser history and the hash router but maybe you needed a very minimal solution that works anywhere?

Is it used at  Freedcamp (hence the prefix `fc`?) to solve a problem that other libraries don't solve? Yes I checked who you were 😄 !

If it's all about the bundle size, maybe you could add a comparison table using data from https://bundlephobia.com/package/fc-hash-router@1.0.2 

> 1.6kB Minified + Gzipped

Linking a related issue https://github.com/sorrycc/awesome-javascript/pull/794 for the records.

Thank you for your feedback, and sorry if I missed obvious points!
