### ISSUE TITLE
Add Arc2D.com

### ISSUE THREAD

**Issue by Nashorn** [michaelrambeau/bestofjs#428]
It does not have 100 stars. I am trying to get traction, very difficult.
Have a look:

[arc2d.com](www.arc2d.com)

**Comment by michaelrambeau** [comment]
Hello @Nashorn 
Thank you for the recommendation.
I guess it's this repo: https://github.com/Arc2D-Framework/Arc2D

The README.md is almost empty, it would be nice to get an overview of the project because the navigation through https://www.arc2d.com/resources is a bit weird to me (I have the impression that nothing happens when I click on the sidebar menu entries, I'm not sure it's because everything is collapsible and you have to find the leaves of the tree, or because it takes time to load the pages... something unusual happens).

For example, I wanted to check how to get started, but you have to click 4 times: Getting started => Basic set up => Download => Download (again!!!)

![image](https://user-images.githubusercontent.com/5546996/138361607-05b6e901-6fef-4322-b339-4b81ba5f3963.png)

Besides that, how do you start using it without downloading manually the repo, is it available on any CDN?

So is Arc2D a set of "web components!? Could it be tagged under the "UI framework" and "Web components"?

Thank you for your feedback!

**Comment by Nashorn** [comment]
Hi Michael
Let me correct these issues and I'll email you back.

**Comment by Nashorn** [comment]
Revamp in progress

**Comment by michaelrambeau** [comment]
Hello @Nashorn thank for the update you shared by email.

What would be the correct tags to apply to the project in _Best of JS_?

I'm thinking about these tags:

- Game engine
- Canvas
- Web component

It could be tagged "UI framework" too since it can be used to build any component in a web page, not just games, if I understand well?

Now we don't have a tag `Physics` but I think it would be nice as we have several projects related to Physics and animation.

**Comment by Nashorn** [comment]
It can appropriately be tagged with all 3 Michael. Current large scale project I am on, we are using it for building simulations/training for military, as HUD (heads-up-display) over a Unity game. Falls under "canvas" tag because it offers the input-update-render game loop environment for canvas api painting.

And definitely under web/mobile development.

There is no built-in Physics api, instead Bullet/Ammo/Box2D can be imported and ran in the upload-loop mentioned above, so a physics tag is not needed.

**Comment by michaelrambeau** [comment]
OK @Nashorn , I tought about the _Physics_ tags because I noticed this block in the homepage:

![image](https://user-images.githubusercontent.com/5546996/142384123-4c43f5bb-84c1-4411-8fb5-fda7bbdcdf3f.png)

but I've just realized there is a "Pro" mention, does it mean the library is split between a free "core" and "paid" extras?

I will create the Physics tag anyway because I like Physics 😄

**Comment by Nashorn** [comment]
Hey Michael,
the Core version is free. The Pro version will also be free when released and will be more geared as a 2D/3D platform for time-sensitive simulations of canvas drawings, threejs etc; with push-down automata state machines for character and NPC behaviors; SAT collisions; Any physics engine can be leveraged and ran inside the optimized input-update World loop, there are no requestAnimationFrames calls, but work like Unity. Pro version will be setup with a bit more intricacy and it's still in the works.

One thing i'll add; We may revamp internals for ECS.

**Comment by michaelrambeau** [comment]
Hello @Nashorn
The day has come.
_Arc 2D_ is now available on _Best of JS_, thank you for your patience!

And we we have a `Physics` tag too https://bestofjs.org/projects?tags=physics

Any feedback about _Best of JS_ is welcome!

![image](https://user-images.githubusercontent.com/5546996/142699346-0497eead-1963-412f-be00-5994229de2aa.png)
