### ISSUE TITLE
Add `auth0/auth0.js` project

### ISSUE THREAD

**Issue by martinheidegger** [michaelrambeau/bestofjs#45]
https://github.com/auth0/auth0.js
While not exactly an open source library, I have heard more and more web developers talk about auth0

**Comment by michaelrambeau** [comment]
I am a huge fan of Auth0, I use their service to authenticate users to bestof.js.org.

But since it's not exactly an open source tool, it's the library to use auth0 service and nothing else, I put the request on "stand-by", because I think we need something to gather the "best services" related to web applications, as we said during a previous discussion (CDN, authentication, i18n, DbaaS...).

**Comment by martinheidegger** [comment]
To be fair: this is true for #43 as well. But a SaaS is still a solution for a problem happening in the JS world.

**Comment by michaelrambeau** [comment]
Yes, I may end up adding the project in a "SaaS" category, that would be the simplest solution. 
And the motto would be: If it's a great service and if it's on Github, let's add it to bestof.js.org.
Let me think a little :)
