### ISSUE TITLE
Add AnyChart

### ISSUE THREAD

**Issue by andreykh1985** [michaelrambeau/bestofjs#460]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 
https://www.anychart.com
https://github.com/anychart/anychart
https://www.npmjs.com/package/anychart

Before submitting the request to add a new project, please check the following points:

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Charting
SVG
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello @andreykh1985 
Thank you for the suggestion, `AnyChart` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @andreykh1985 
Sorry for the delay, `AnyChart` is now available on _Best of JS_.
It took time because actually `AnyChart` was already tracked by Best of JS but it was not visible in web application because it was considered as a project with little traction (less than 100 stars added over the last 12 months).
So I had to change the criteria, lowering this threshold of 100 stars/year, so that the project is visible.
Please check, thank you for your feedback!
