### ISSUE TITLE
Add React Native Starter Template

### ISSUE THREAD

**Issue by stepnov** [michaelrambeau/bestofjs#507]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A powerful react native starter template that bootstraps development of your mobile application. React Native Starter is a mobile application template with lots of built-in components like sidebar, navigation, form elements, etc - all you need to start building your mobile app faster.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/flatlogic/react-native-starter

**Before submitting the request to add a new project, please check the following points:**

- [] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Mobile, React Native

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Eugene @stepnov 
Thank you for the recommendation.
I wonder if the project is still actively maintained because the last release is... 2 years ago (and we know that 2 years  in the JavaScript landscape means the eternity, right? 😄)
I also noticed that some important questions got no answer https://github.com/flatlogic/react-native-starter/issues/67
Thank you for your feedback!
