### ISSUE TITLE
Testem

### ISSUE THREAD

**Issue by ascudder** [michaelrambeau/bestofjs#522]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Testem is a JavaScript test runner that supports multiple testing frameworks and execution environments (Node, major browsers).

It is used by the community in projects such as by Ember.js's application testing blueprints.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/testem/testem

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Testing, Testing Framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Ember

**Comment by michaelrambeau** [comment]
Hello Andrew @ascudder thank you for reaching us!

Actually `Testem` project was tracked by _Best of JS_ since 2016 but it was filtered out in the UI because of a rule that tries to filter out projects considered as "cold". The threshold was `25` new stars by year on GitHub and `Testem` only got 20 stars. Anyway I adjusted the rule to take into account the number of downloads on NPM.

https://github.com/bestofjs/bestofjs-backend/blob/master/cli/tasks/projects/build-projects-files.task.js#L151

As a result `Testem` is back on _Best of JS_, please check here https://bestofjs.org/projects/testem
Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/201796732-0e4815d9-2f83-48b3-b090-3e048f7b9c6a.png)

**Comment by ascudder** [comment]
@michaelrambeau Ah, interesting! Thank you for the update and re-adding it
