### ISSUE TITLE
New project: Wireit

### ISSUE THREAD

**Issue by rictic** [michaelrambeau/bestofjs#578]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Wireit upgrades your npm scripts to make them smarter and more efficient.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/google/wireit/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Building tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by rictic** [comment]
Ah, this is a dupe of https://github.com/michaelrambeau/bestofjs/issues/571

However I do think that it should be listed under building tools, as it serves a similar role to gulp in orchestrating and scheduling build work

**Comment by michaelrambeau** [comment]
Hello @rictic thank you for the feedback.

A tag `building tool` has been added to `Wireit` https://bestofjs.org/projects/wireit

![image](https://user-images.githubusercontent.com/5546996/204938597-6c5bdc4c-132f-4fa6-ab71-7c1f6c105333.png)

We may need a more specific tag for this category of tools that help handling NPM scripts (maybe `NPM scripts`) rather than actually building stuff.
