### ISSUE TITLE
Add `rusher81572/picluster` project

### ISSUE THREAD

**Issue by rusher81572** [michaelrambeau/bestofjs#58]
https://github.com/rusher81572/picluster
A powerful way to orchestrate Docker containers in Node.js

**Comment by michaelrambeau** [comment]
Hello @rusher81572  , I am embarrassed because I'm not familiar with Docker so I don't understand well the purpose of the project.
It seems that your built your project with node.js but it does not seem to be a project related to JavaScript and/or web development.
For now it doesn't seem to match the target of bestof.js.org ("The best components to build amazing web applications!") 
On the other hand, one may say that you may need Docker to deploy a node.js project, so your project is related to web applications... it really depends on the point of view!
So I may create a new tag called "Docker" or "Container" in the future, for now I put your request on stand-by.

I don't like to decline suggestions and I respect creators of open source projects like yours.
Let me know if your have other arguments, I may change my point of view at any time (no later than tomorrow maybe!), this is not a definitive "no".
Thank you for your understanding!
