### ISSUE TITLE
Add `oh-my-fetch` to the Data fetching libraries

### ISSUE THREAD

**Issue by qnp** [michaelrambeau/bestofjs#588]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Newly written type-proof universal fetcher with a nice API (core of Nuxt 3)

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/unjs/ofetch

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Data fetching

**Comment by michaelrambeau** [comment]
Hello François @qnp thank you for the recommendation, `ofetch` will be available on _Best of JS_ very soon.

It would be tagged `HTTP client / AJAX` instead of `Data fetching` as it's a low-level alternative to the native `fetch` feature: https://bestofjs.org/projects?tags=http

And maybe the tag could be renamed `HTTP client / Fetch / AJAX` as using `fetch` in the browser is now more popular than using AJAX requests 🤔 ?

**Comment by michaelrambeau** [comment]
Hello François @qnp `ofetch` is now available on _Best of JS_, please check.

Also the tag I mentioned was renamed `HTTP client • Fetch • AJAX`, let me know if it makes sense, thank you!

https://bestofjs.org/projects?tags=http

![image](https://user-images.githubusercontent.com/5546996/205764640-29e768dc-d426-424a-9985-696f74c15ef4.png)

**Comment by qnp** [comment]
Thanks Michael, sounds perfect. I think the tag you choose is consistent.

Yet, I suggested that lib because it was missing in State of Javascript Survey - but they chose the tag "Data fetching" for the Fetch libraries list, I guess I thus won’t be seen in that survey ?
