### ISSUE TITLE
Add Qwik City as option to Rendering Frameworks

### ISSUE THREAD

**Issue by bradfrosty** [michaelrambeau/bestofjs#589]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Qwik City is the meta framework Qwik, similar to Next for React or SvelteKit for Svelte.

**What is the URL of the project you'd like to add to _Best of JS_?**

- https://qwik.builder.io/qwikcity/overview/
- https://github.com/BuilderIO/qwik/tree/main/packages/qwik-city

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Full-stack Framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Brad @bradfrosty I think you are asking about the State of JS survey, not about the site _Best of JS_ projects as the tag "Rendering framework" does not exist in _Best of JS_?

I cannot change the categories in the survey, sorry!

Actually `Qwick City` project is part of `Qwik` repo that is already tracked by _Best of JS_: https://bestofjs.org/projects/qwik

The problem is that we can track only one project by GitHub repo, we need a way handle monorepos in a better way.
