### ISSUE TITLE
@microsoft/heft

### ISSUE THREAD

**Issue by NEWESTERS** [michaelrambeau/bestofjs#593]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Typescript build orchestrator

**What is the URL of the project you'd like to add to _Best of JS_?**
https://rushstack.io/pages/heft/overview/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Building Tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @NEWESTERS thank you for the suggestion, actually `@microsoft/heft` is part of Rush repository, that is already tracked by _Best of JS_: https://bestofjs.org/projects/rush

The problem is that we can track only one project by GitHub repo, we need a way handle monorepos in a better way, we have a similar problem with other monorepos like https://github.com/adobe/react-spectrum
