### ISSUE TITLE
Add Leptos Framework

### ISSUE THREAD

**Issue by SpicyRicecaker** [michaelrambeau/bestofjs#599]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Leptos

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/gbj/leptos

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Full-stack framework, Web Assembly, Universal, Reactive Programming
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Rust

**Comment by michaelrambeau** [comment]
Hello @SpicyRicecaker thank you for the recommendation.

So far _Best of JS_ only includes backend frameworks written in TS or JS.
However I'm aware that the scope of the project is blurry. There are solution like _Tauri_: it's written in Rust but I added to _Best of JS_ because you don't have to write Rust code to use it and build Desktop apps.

Let me know what you think... maybe we need another project `Best of Rust` 😄

**Comment by SpicyRicecaker** [comment]
I see, thanks. I think that Leptos does use calls to javascript under the hood with wasm bindgen, but the user-facing side is completely Rust. A Best of Rust might be pertinent a year or two down the line when wasm gets better and better tho! Thanks for considering.
