### ISSUE TITLE
Add JSON Crack

### ISSUE THREAD

**Issue by AykutSarac** [michaelrambeau/bestofjs#615]
**Please briefly describe the project you'd like to add to _Best of JS_?**
JSON Crack – the open-source, free JSON visualization app that will revolutionize the way you work with data. With its intuitive and user-friendly interface, JSON Crack makes it easy to explore, analyze, and understand even the most complex JSON structures. Whether you're a developer working on a large-scale project or a data enthusiast looking to uncover hidden insights, JSON Crack has the tools and features you need to unlock the full potential of your data.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/AykutSarac/jsoncrack.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React, JSON, Next.js, Validation, Diagram / Flow chart

**Comment by michaelrambeau** [comment]
Hello @AykutSarac thank you for the recommendation.

JSON Crack will be available on _Best of JS_ very soon.

Note: it seems the link https://jsoncrack.com/embed in the README.md is wrong, leading to a page that says: "Looks like you're lost, let's head back to the home!"

I wonder if we need a new tag "Online tool" for this kind of project, since it's not a library you can use directly in your code (or maybe the existing "Dev tool" is enough, like for JSON Hero project: https://bestofjs.org/projects/json-hero ?

**Comment by AykutSarac** [comment]
Hey, thanks for the heads up I've updated the link. I think "Dev tool" is enough instead of "Online tool".

Excited to see it on live, thank you!

**Comment by michaelrambeau** [comment]
Hello @AykutSarac `JSON Crack` is available on _Best of JS_, please check here: https://bestofjs.org/projects/json-crack
