### ISSUE TITLE
Add PureORM

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#638]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A pure ORM for writing native SQL queries yielding pure business objects

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/craigmichaelmartin/pure-orm

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- SQL
- ORM

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for the suggestion, `Pure ORM` was already tracked by _Best of JS_ but it was no more included in the app because it was considered as a "cold" project, due to the lack of traction, as we have a mechanism to try to keep only "relevant" projects.

So I added a way to "promote" some projects bypassing he rules to filter out cold projects, so that some projects can show up even if they lack of traction.

Please check here: https://bestofjs.org/projects/pureorm

Related to this commit in the backend: https://github.com/bestofjs/bestofjs-backend/commit/a73b6a234daafa980e4738c9ad3129eb65e21f2d

**Comment by xeusteerapat** [comment]
@michaelrambeau  Thanks for the update 🙂
