### ISSUE TITLE
Debate - Separate Webassembly lib from  pure Javascript lib

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#640]
There is more and more non JS projects proposing Webassembly version to be used in browser
Webassembly give lot of opportunity like fast lib using SIMD, multithread, low level code, no Garbage Collection...
https://robaboukhalil.medium.com/webassembly-and-simd-7a7daa4f2ecd

However, it's a bit weird to propose a non JS project in BestOfJS because well... is not JS project

On bestofjs website, Should we create some new pages to promote Webassembly and very fast C/Rust/... lib
- Webassembly lib version of C/Rust lib... which can be more optimized for some use case 
(optimized database written in C directly in browser...)
- Webassembly advice & tools to compile any C/Rust/... into Webassembly
...

I'm thinking to project Pyodide, which allow to use lots of Python libs inside browser
It's just allowing to take advantage of Python community to make data science
It is a popular project (9k start) but it is not defined in BestOfJS, but it's a pure webassembly lib
https://github.com/pyodide/pyodide

What do you think ?

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 thank you for opening the debate!

We have already a category "Compiler" that includes languages that compile to JavaScript (some languages are specific to web applications like Elm but there are also real server-side programing languages like Scala).
Also we have some projects that let users create desktop application using web technologies that are written in languages like Rust (Tauri).

So it makes sense to accept in the `Web Assembly` category projects that let users run Python in the browser.

https://bestofjs.org/projects?tags=webassembly

![image](https://user-images.githubusercontent.com/5546996/226801014-c38378aa-eb66-4c3c-83cd-b907189adeae.png)

Maybe we should update the communication around the project, because it's not just about JS and friends.
it's also about anything that can run the browser using web assembly?

**Comment by bluehat974** [comment]
Indeed, there is webassembly & compiler tags available.

I think the communication could be updated (best of web ? 😅 but you will lose SEO), 
it's not JS projects but everything that can run in the browser/nodejs using webassembly.

I launch this conversation because webassembly becore more & more important and BestOfJS is not just about JS now.

But for now, you don't need to do more, I will add webassembly project in the webassembly tags.
