### ISSUE TITLE
Add Rest-hook

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#678]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Normalized state management for async data. Safe. Fast. Reusable.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://resthooks.io/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Data fetching
- Hook
- GraphQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Rest Hooks` is available on _Best of JS_, please check.

https://bestofjs.org/projects/rest-hooks

Note: the `hooks` tag is assigned on libraries that provide multiple features as a collection of hook, like `react-use`, not just on libraries that provide hooks (otherwise I would have to tag a lot of React projects), it's a bit misleading, sorry, I should clarify by providing a clear description of each tag.

**Comment by xeusteerapat** [comment]
@michaelrambeau No worries, thanks for the clarification 🙂
