### ISSUE TITLE
Add `tjwebb` user to the Hall of Fame

### ISSUE THREAD

**Issue by tjwebb** [michaelrambeau/bestofjs#68]
https://github.com/tjwebb
Creator of Trails.js

**Comment by michaelrambeau** [comment]
Hello @tjwebb 
It's the first time someone is asking to be inducted in the the JavaScript Hall of Fame by oneself!

Usually I check the number of followers and I accept the requests if I see numbers greater than 1000.
You have 299 followers so I'm going to follow you so that I can justify you need 300 followers to be a valid candidate, if jealous people ask for the criteria to enter the Hall of Fame ;)

The Hall of Fame page will be rebuilt in 24 hours, be patient, I will confirm when it's online.

**Comment by tjwebb** [comment]
Haha hey, no worries. I had just discovered your website yesterday when Google Analytics showed me that a bunch of traffic for Trails was coming from your site. I was mostly messing around to see what you all were about :)

If you'd like to add me to your Hall of Fame, I certainly won't complain. If not, no worries.

**Comment by michaelrambeau** [comment]
Hello @tjwebb ,
I'm happy to announce that you are the first self-inducted member of the [JavaScript Hall of Fame](http://bestof.js.org/hof), congratulations!
Don't forget to update your resume 😃 

If you have any feedback about the application, feel free to contact me.

**Comment by tjwebb** [comment]
> Don't forget to update your resume

sure thing. hell, put it in my obituary! thanks

**Comment by michaelrambeau** [comment]
@tjwebb Travis, you're welcome!

Just a question, when you mentionned 'a bunch' of traffic, is it from the app itself (bestof.js.org) or is it from [2016 JavaScript Rising Stars](https://risingstars2016.js.org/) article, where Trails project is number 10 in the `node.js frameworks` category?

**Comment by tjwebb** [comment]
The traffic seems to be coming from bestofjs.org

**Comment by michaelrambeau** [comment]
Alright, it's good to know. And that's just the beginning, soon the application will bring you tons of visitors! 😉
