### ISSUE TITLE
Add `turbolinks/turbolinks` project

### ISSUE THREAD

**Issue by serradura** [michaelrambeau/bestofjs#75]
https://github.com/turbolinks/turbolinks
Because Turbolinks is an awesome tool to create great web apps with less effort and ship hybrid native apps.

**Comment by michaelrambeau** [comment]
Hello Rodrigo @serradura 
Thank you for the suggestion, the project will be available on bestof.js.org very soon.

Just in case, do you know how Turbolinks compares with this project: http://intercoolerjs.org/ ?

Intercooler project seems to be more active than Turbolinks, maybe because TurboLinks is written in CoffeeScript and seems to be a project close to the Rails community.

**Comment by michaelrambeau** [comment]
Hello again Rodrigo @serradura 

Turbolinks project is available on bestof.js.org: http://bestof.js.org/projects/turbolinks

Please let me know if you have any feedback!
