### ISSUE TITLE
Add Alacritty to Best of JS

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#783]
**Please briefly describe the project you'd like to add to _Best of JS_?**

- modern terminal emulator

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

- https://github.com/alacritty/alacritty

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and the project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- CLI

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Jacob @jacobthesheep thank you the recommendations (this one and the other ones!)

This CLI emulator project seems to be a project in Rust (not like Tabby or Hyper for example) so I wonder if it qualifies?

However I'm aware that the boundaries are blurry as we have projects in Rust related to the tooling 😅 
I guess your reasoning is that it relates to web technologies because you use it as your terminal to run web projects?
It's just that I'm afraid we would miss many similar projects if we try to track all terminal emulators...

Let me know what you think, thank you for your help!

**Comment by ghost** [comment]
True, I guess it shouldn't be added to prevent the boundaries from becoming more blurry.
