### ISSUE TITLE
Add `hydrabolt/discord.js` project

### ISSUE THREAD

**Issue by amishshah** [michaelrambeau/bestofjs#80]
https://github.com/hydrabolt/discord.js
Discord.js is a node.js/JavaScript library that allows developers to interact with the Discord API

**Comment by michaelrambeau** [comment]
Hello Amish @hydrabolt 
Thank you for the recommendation.
I wonder which tags would be appropriate, would `realtime` be OK (since there is no `chat` tag)?
http://bestof.js.org/tags/realtime

Also, since it's related to an online service (and not something you install on your own server), I wonder if we should create a specific section to gather the best of "online services" (authentication services like Auth0, database as a service, hosting, online playground like jsbin...)

See #45

**Comment by amishshah** [comment]
real-time sounds good to me! And yes, I think an online services section would be great also

**Comment by michaelrambeau** [comment]
Hello Amish @hydrabolt 
It's online, check here for example http://bestof.js.org/tags/realtime

**Comment by amishshah** [comment]
Thanks!
