### ISSUE TITLE
Add `jschr/bootstrap-modal` project

### ISSUE THREAD

**Issue by jschr** [michaelrambeau/bestofjs#84]
https://github.com/jschr/bootstrap-modal
popular alternative to BS2/3 modals

**Comment by jschr** [comment]
I closed this issue and #85 and #86 because I didn't realize bestofjs was manually curated and a small list of repos. I stumbled upon the site and added my own repos without really thinking about it.

Sorry for the noise.

**Comment by michaelrambeau** [comment]
Hello Jordan @jschr 
Don't be sorry, I didn't know about your projects, if they are good and up-to-date, there is no problem about suggesting them!
The list of projects is manually curated indeed because so far I have not found any automatic way to find the "Best of JavaScript".

This is why I rely on the community (asking for suggestion to projects to add).
If you have any idea to create an algorithm to make things automatic or improve this system, let me know.

My main goal is show the projects that are relevant right now.
I don't want to show projects based only on their total number of stars because popular projects at a given time can deprecate a few months later.

Thank you in advance for your feedback!

**Comment by jschr** [comment]
I think the manual curation is what separates your site from similar sites like [github ranking](https://github-ranking.com/). I like that it showcases relevant (and active) but not necessarily popular projects. I just didn't notice that before submitting :)

Thanks for the hard work!
