### ISSUE TITLE
Add svgl

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#871]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A beautiful library with SVG logos. Built with Sveltekit & Tailwind CSS.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/pheralb/svgl

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Icon set

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @jacobdalamb for the recommendation, `svgl` is available on _Best of JS_.

https://bestofjs.org/projects/svgl

Note that I have gathered a good amount of SVG logos over the time, to show nice logos instead of the GitHub owner avatars, for more than 280 projects:

https://github.com/bestofjs/bestofjs/tree/develop/apps/bestofjs-nextjs/public/logos 

So we could create a similar project 😄 !
