### ISSUE TITLE
Add `atomixinteractions/createrest` project

### ISSUE THREAD

**Issue by sergeysova** [michaelrambeau/bestofjs#88]
https://github.com/atomixinteractions/createrest
Just create REST routes for your Node.js application

**Comment by michaelrambeau** [comment]
Hello Sergey @LestaD 
Thank you, your project will be available on bestof.js.org very soon.

Just a suggestion to make your project more popular, could you add more explanation in the README.md:

* About **why** you built this project, explaining which boilerplate code you can avoid typing by using `createrest`instead of only Express basic routes.
* About how it works
  * what is a "scope" (I guess it's a kind of subdomain to group several routes that start with the same key together) ?
  * How hooks work, what is their signature (I guess they are Express middleware `(req, res, next) => {}`) ?

**Comment by sergeysova** [comment]
@bestofjs `scope` is a group for routes and before/after hooks.

By default createrest do not define signature for hooks, it passed to target http library(express/koa). Now supports only express: [createrest-express](https://atmx.in/rest-ex).

I will add boilerplate code in near future

**Comment by michaelrambeau** [comment]
Hello Sergey! @LestaD 
`createrest` project is available on bestof.js, check this category for example: http://bestof.js.org/tags/routing

When you have time, please don't forget to add more explanation in the README.md about the **purpose** of the project, I think you have to tell users what is the benefit of using `createrest` rather than normal Express code.

> Declare your routes

...  is a bit too short, you have to "sell" your project to be more popular.

Anyway, it's only an advice, we try to gather the "best" projects related to the web platform and **good documentation** is really important.

Thank you for your understanding, let me know if you have any feedback about bestof.js.org!

**Comment by sergeysova** [comment]
@michaelrambeau Thank you!
