### ISSUE TITLE
Add vscode-symbols

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#886]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A file icon theme for VS Code

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/miguelsolorio/vscode-symbols

**Before submitting the request to add a new project, please check the following points:**

- [?] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Icon Theme

**Comment by michaelrambeau** [comment]
Thank you for the suggestion @jacobdalamb  we don't have a tag for such a specific topic: customization of the look-and-feel of an IDE, but what do you think, should we create it? (the downside being that people would complain: "why this `vscode-symbols` project is the only IDE theme you know?", you know what I mean?)

Otherwise we can consider the project a collection of icons and tag it `Icon Set`, what do you think?

**Comment by ghost** [comment]
> Thank you for the suggestion @jacobdalamb we don't have a tag for such a specific topic: customization of the look-and-feel of an IDE, but what do you think, should we create it? (the downside being that people would complain: "why this `vscode-symbols` project is the only IDE theme you know?", you know what I mean?)
> 
> Otherwise we can consider the project a collection of icons and tag it `Icon Set`, what do you think?

Yeah, `Icon Set` would be better and if people start to add more IDE theme sets then we can reconsider adding a new category.

**Comment by michaelrambeau** [comment]
OK `vscode-sysmbols` is available on _Best of JS_.

https://bestofjs.org/projects/vscode-symbols
