### ISSUE TITLE
Add Derby

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#945]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- MVC framework making it easy to write realtime, collaborative applications that run in both Node.js and browsers

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/derbyjs/derby

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Node.js framework
- Full-stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Derby` was tracked by _Best of JS_ but it was not showing up in the app because it was considered as a "cold" project (losing stars). I made a change to "promote" it and by pass the default filter.

In the future we should find a way to let people see all projects we track (around 3,000 projects, instead of the 2,000 projects showing in the UI).

https://bestofjs.org/projects/derby

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/b20144b3-29de-40f0-800e-b1d1b787e39f)
