### ISSUE TITLE
Add InstantSearch.js project

### ISSUE THREAD

**Issue by bobylito** [michaelrambeau/bestofjs#96]
Hi there,
Could you add InstantSearch.js? It's a library to easily build search UI with Algolia.

https://community.algolia.com/instantsearch.js/v2/
https://github.com/algolia/instantsearch.js/
https://www.npmjs.com/package/instantsearch.js

> InstantSearch.js makes it easy to design the perfect search experience using prepackaged search widgets or by creating your own!

**Comment by michaelrambeau** [comment]
Hello Alex @bobylito 
Thank you for the suggestion, I'm adding `InstantSearch.js` project, it will be online very soon.

FYI there are already 3 projects from Algolia in Best of JS: https://bestof.js.org/search/algolia
Including `React InstantSearch` which is built on top of `InstantSearch.js`, I guess?

![image](https://user-images.githubusercontent.com/5546996/28643506-0167c328-7291-11e7-872d-e51d6f6af140.png)

**Comment by bobylito** [comment]
Woh thanks a lot 🎉 

I saw that there were already some of the Algolia front-end libraries that's why I opened the issue :)

> React InstantSearch which is built on top of InstantSearch.js, I guess?

Actually no. We plan to make all the instantsearch libraries converge at some point but react-instantsearch was created from scratch. They use a common middleware though :)

**Comment by michaelrambeau** [comment]
@bobylito  It's online! For example, check  the following URLs:

* Searching for `algolia` keyword https://bestof.js.org/search/algolia 
* The `Full-text search` tag: https://bestof.js.org/tags/search

Since you are a specialist of the research on the web, any feedback about BestOfJS search module is welcome!
I wanted the search module to be blazing fast because I was fed up with always googling about the same projects ;)

**Comment by bobylito** [comment]
You're awesome, thanks for adding instantsearch.js 🎉 

If you want we can discuss about that on a different channel, you can reach me by email at bobylito at algolia :)
