### ISSUE TITLE
Add Coolify to Best of JS

### ISSUE THREAD

**Issue by BBlackwo** [michaelrambeau/bestofjs#964]
**Please briefly describe the project you'd like to add to _Best of JS_?**

An open-source & self-hostable Heroku / Netlify / Vercel alternative. https://coolify.io

Not sure if it's relevant enough to fit in BestOfJS though 🤔 

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/coollabsio/coolify

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The source code is on GitHub and project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Not sure 😅 Maybe `build`, `db`, `dashboard`? It can deploy basically any tech stack so probs not worth tagging specific tech.

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Maybe a `ci` tag?

**Comment by michaelrambeau** [comment]
Thank you @BBlackwo , for visibility, I'm sharing here what we discussed on Discord:

In the past I have rejected great "backend as a service!" projects like AppWrite (https://github.com/appwrite/appwrite) because they were not JS, and a lot of projects may be missing if we extend the scope of Best of JS.
But I'm not sure if this choice makes sense... from your point of view what would be the arguments that make Coolify a project that belongs to Best of JS?
Note that we have a "Backend as a Service" tag, but only 3 projects for now, led by Supabase: https://bestofjs.org/projects?tags=baas

(ongoing discussion on Discord)

**Comment by michaelrambeau** [comment]
OK @BBlackwo following the discussion we had on Discord, `Coolify` was added to _Best of JS_, under the new tag "Self hosted", that we use for some open-source alternatives to great services.

It's an exception to the rule related to the main language because of its unique status of alternative to services like Vercel and Netlify.

https://bestofjs.org/projects/coolify
