### ISSUE TITLE
bem.js

### ISSUE THREAD

**Issue by JostCrow** [michaelrambeau/bestofjs#99]
https://github.com/maykinmedia/bem.js

DOM selection and manipulation using BEM (Block, Element, Modifier).

**Comment by michaelrambeau** [comment]
Hello again @JostCrow ,
This is your request number 2, thank you!

Could you provide some background information about why you created this project?
Some use cases? 

I know BEM but I have the impression that it's less popular then before, especially because of the components trends and the "CSS-in-JS" wave.

Have a look at this article, it's one of the best things I read about the right way of styling things in the browser:
https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660

**Comment by svenvandescheur** [comment]
Hi @michaelrambeau 

I'm a colleague of @JostCrow and the author of [https://github.com/maykinmedia/bem.js](bem.js) and [https://github.com/maykinmedia/consumerjs](consumerjs) (not dual-listbox). I'll try to answer your questions.

 > Could you provide some background information about why you created this project?
Some use cases?

The original source code was part of a project we maintain. The project had issues scaling it's stylesheets and the components that were in place loosely followed the "atomic design" pattern which led to confusion among (non frontend) developers and had some issues according to our standards and opinions (like scoping).

We migrated towards BEM and started this project as utility library to support that migration. It's now the go to tool for our projects (and our customers) whenever (M)V(C) frameworks like React are not needed.

At the same time we were migrating towards a more modern stack (ES6 over jQuery) and redesigning out frontend architecture. In order to provide modern alternatives to jQuery we came up with 2 projects.

- $.ajax -> ConsumerJS, implement an ORM like approach to XHR (we're still working on the R in ORM).
- DOM manipulation -> BEM.js, this one.

We use BEM because:

- Easy to read and understand without any background knowledge.
- No globals, everything is scoped / well contained.
- Clear state classes using modifiers.
- Large user base.

The goals of this library are:

- Be as stateless as posible (makes it easier to use with other (template) systems.
- Provide functions that allow DOM manipulation based on BEM conventions.
- Encourage seperations of concerns (change state from JS, layout from CSS).
- Encourage a consistent approach to working with the DOM.

 > I know BEM but I have the impression that it's less popular then before, especially because of the components trends and the "CSS-in-JS" wave.

I don't agree, there is definitely a lot of fuzz around "CSS in JS" but in practice (we work a lot with other parties) we increasingly see BEM based projects and we almost never encounter setups that use CSS in JS. 

Other than that, I personally think that embedding style (not structure) within a library is bad practice. Basically because:

- When we reuse code, we almost always exclusively reuse JS/HTML code, styling is specific to each customers. Containing CSS in a JS module will cause styling conflicts.
- CSS in JS may be harder to optimize (depending on your stack).

For instance, @JostCrow 's dual-listbox only provides a bare minimum of (importable) styling which is easily customized and doesn't require a specific frontend stack.

**Comment by michaelrambeau** [comment]
Hello @svenvandescheur and @JostCrow 

Thank you for the feedback, the `bem.js` project will be available on BestOfJS very soon.

It will be under the tag `css-in-js`, because I cannot see a more appropriate tag right now, does it make sense for you too?

**Comment by svenvandescheur** [comment]
Hi @michaelrambeau 

Thanks for accepting BEM.js. "CSS in JS" makes some sense but I think it fits better in "DOM manipulation" as the main purpose of this library to provde "BEM based" DOM manipulation.

**Comment by michaelrambeau** [comment]
Hello @svenvandescheur 

Yes, you are right, `DOM manipulation` is the right tag.

`BEM.js` project is available here https://bestof.js.org/tags/css-in-js but the tag will be fixed in 24 hours, next time the project is built.

I will let you know when it's fixed.

**Comment by michaelrambeau** [comment]
Hello @svenvandescheur and @JostCrow 

It's live! 

Check the `DOM manipulation` tag here: https://bestof.js.org/tags/dom

Let me know if you have any feedback about the application, thank you in advance!
