### ISSUE TITLE
Add Handbrake-js

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#996]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Video encoding / transcoding / converting for node.js

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

**Before submitting the request to add a new project, please check the following points:**
- https://github.com/75lb/handbrake-js

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Video

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat actually handbrake-js is already tracked by _Best of JS_ (you asked last year #670 😅 ) but it does not show up because of the following metrics:

- 25 stars added over the last year
- about 2.5k monthly downloads on NPM

What do you think, I can "promote" the project and ignore this filter?

Note: I set a filter based on metrics to avoid displaying in the UI projects considered as "cold" because they are often less relevant, as projects tend to deprecate over time, this is the reason the current UI shows about 2000 projects while we track more than 3000 projects.

**Comment by michaelrambeau** [comment]
@xeusteerapat I have "promoted" Handbrake.js to skip the filter about "cold" projects:

https://bestofjs.org/projects/handbrake.

![image](https://github.com/user-attachments/assets/552fbbce-73e1-4746-9ea6-fbbbade01e27)

**Comment by xeusteerapat** [comment]
Ahh, got it. That's why it looks familiar to me 😅
